#ifndef FOLLOW
#define FOLLOW

//#include "states.h"

//int tok_list_len  = 277; //number of tokens

struct follow_list{
	int id;
	int fol[277];
	int len;

};


int fol_list_set_len = 277;

struct follow_list follow_list_set[] = {


//tokens follow list
//this set is obsolete, please refer to sehvler_3.h for latest follow set
{ PRG , { }, 0 }, 
 { VAR , { }, 0 }, 
{ TAM , { IDT }, 1 }, 
{ KESR , { IDT  }, 1 }, 
{ SIMVOL , { IDT  }, 1 }, 
{ IDT , { POSSIG,   ASGN, NOQTEV, VERGUL, GRT,  CLSBRK, ARYCLS, ARYBRK_VAL, DECREMENT,  BRK_EMP, BRK_VAL, BRK_SEQ, }, 12 }, 
{ VERGUL , { IDT }, 1 }, 
{ NOQTEV , { }, 0 }, 
{ KOD , { }, 0 }, 
{ CAPET , { }, 0 }, 
{ OPNBRK , { CLSBRK, IDT,  SHERT,  SEQ,  }, 4 }, 
{ STR , { CLSBRK, }, 1 },   
{ CHR , { POSSIG,  NOQTEV,  VERGUL,   GRT,  CLSBRK, ARYCLS    }, 6}, 
{ CLSBRK , { }, 0 }, 
{ SON , { }, 0 }, 
{ DOT , { }, 0 },   
{ LEXEM , { }, 0 }, 
{ NUMB , { POSSIG,  NOQTEV, COLON, VERGUL, GRT,  CLSBRK, ARYCLS }, 7 }, 
{ SIGN , { }, 0 }, 
{ DIG , { }, 0 }, 
{ POSDIG , { }, 0 }, 
{ POSNUMB , { }, 0 }, 
{ SNUMB , { }, 0 }, 
{ POSSIG , { IDT  }, 1 }, 
{ NEGSIG , { IDT  }, 1 }, 
{ SLC , { }, 0 }, 
{ MLC , { }, 0 }, 
{ SPS , { }, 0 }, 
{ COLON , { }, 0 }, 
{ ARYOPN , { IDT }, 1 }, 
{ ARYCLS , { }, 0 }, 
{ ASGN , { IDT }, 1 }, 
{ MULT , { IDT  }, 64 }, 
{ DEL , { IDT  }, 64 },
{ PRCT , { IDT  }, 64 },
{ XAR , { }, 0 }, 
{ DAXIL , { }, 0 }, 
{ EGER , { BRK_SHERT, }, 1 }, 
{ NIDA , { }, 0 }, 
{ GRT , { IDT,}, 64 }, 
{ LES , { IDT,}, 64 }, 
{ VE , { SHERT   }, 1 }, 
{ VEYA , { SHERT   }, 1 }, 
{ FILESON , { }, 0 }, 
{ OPNBLK , { CLSBLK, HAL2, KOD_PART, }, 3 }, 
{ CLSBLK , { }, 0 }, 
{ ONDA , { }, 0 }, 
{ YOXSA , { SIMPLE_OPER }, 1 }, 
{ BERABER , { IDT, },64 },
{ FERQLI , { IDT, },64 },
{ LESEQU , { IDT, },64 },
{ GRTEQU , { IDT, },64 },
{ EMPTOK , { }, 0 }, 
{ SHERT , { VE , CLSBRK, }, 2}, 
{ IFAD , { }, 0 }, 
{ DOVR , { }, 0 }, 
{ ARTSIN , { }, 0 }, 
{ AZALSIN , { }, 0 }, 
{ ADDIM , { }, 0 }, 
{ KIMI , { }, 0 }, 
{ CRG1 , { POSSIG,  NOQTEV, ASGN,  VERGUL, GRT,  CLSBRK, ARYCLS, ARYBRK_VAL, DECREMENT }, 9 }, 
{ CRG2 , { POSSIG,  NOQTEV, ASGN, VERGUL,  GRT,  CLSBRK, ARYCLS, DECREMENT,  }, 8 }, 
{ TEKRARET , { }, 0 }, 
{ DAN , { }, 0 }, 
{ DEN , { }, 0 }, 
{ CAPET_OP , { }, 0 }, 
{ DOVR_OP , { }, 0 }, 
{ BLOCK , {  YOXSA, CLSBLK }, 2 }, 
{ BIRTIP , { }, 0 }, 
{ TIPLER , { }, 0 }, 
{ EGER_OP , { }, 0 }, 
{ ASGN_OP , { }, 0 }, 
{ DAXIL_OP , { }, 0 }, 
{ BLOKSUZ , { }, 0 }, 
{ BLOKLU , { }, 0 }, 
{ KODDATALAR , { }, 0 }, 
{ BLOKLUDATA , { }, 0 }, 
{ YE , { }, 0 }, 
{ YA , { }, 0 }, 
{ EE , { }, 0 }, 
{ AA , { }, 0 }, 
{ DOVR_EXP , { }, 0 }, 
{ EGER_EXP , { }, 0 }, 
{ DOVR_BLOKSUZ , { }, 0 }, 
{ EGER_BLOKSUZ , { }, 0 }, 
{ YOXSA_BLOKSUZ , { }, 0 }, 
{ KODDATA , { }, 0 }, 
{ DOVR_BLOKLU , { }, 0 }, 
{ EGER_BLOKLU , { }, 0 }, 
{ YOXSA_BLOKLU , { }, 0 }, 
{ EGER_TEK_BLOKSUZ , { }, 0 }, 
{ EGER_TAM_BLOKSUZ , { }, 0 }, 
{ TAM1 , { }, 0 }, 
{ TAM2 , { }, 0 }, 
{ KESR1 , { }, 0 }, 
{ KESR2 , { }, 0 }, 
{ SIMVOL1 , { }, 0 }, 
{ SIMVOL2 , { }, 0 }, 
{SIMVOL2  , { }, 0 }, 
{ VAR1 , { }, 0 }, 
{ VAR2 , { }, 0 }, 
{ DAXILET1 , { }, 0 }, 
{ DAXILET2 , { }, 0 }, 
{ CAPET1 , { }, 0 }, 
{ CAPET2 , { }, 0 }, 
{ EGER_EXP1 , { }, 0 }, 
{ EGER_EXP2 , { SIMPLE_OPER, }, 1 }, 
{ KOD1 , { }, 0 }, 
{ PRG1 , { }, 0 }, 
{ BADSTR , { }, 0 }, 
{ BADIDT , { }, 0 }, 
{ BADCHR , { }, 0 }, 
{ DAXILET3 , { }, 0 }, 
{ EMPTYOP , { }, 0 }, 
{ CAPET3 , { }, 0 }, 
{ EXPR , { POSSIG, NOQTEV, VERGUL,  GRT,  CLSBRK, ARYCLS }, 6 }, 
{ OPR , { }, 0 }, 
{ BRK , { }, 0 }, 
{ FILEBEG , { }, 0 }, 
{ FLOAT_HALF , { }, 0 }, 
{ FLOAT , { POSSIG,  NOQTEV, VERGUL, GRT,  CLSBRK, ARYCLS }, 6 }, 
{ FUNKSIYA , { FCALL1}, 1 }, 
{ FUNK_ELAN , { }, 0 }, 
{ FUNK_BODY , { }, 0 }, 
{ EMPBRK , { }, 0 }, 
{ FE1 , { }, 0 }, 
{ FE2 , { }, 0 }, 
{ FUNK , { }, 0 }, 
{ FUNKS , { }, 0 }, 
{ FCALL , { }, 0 }, 
{ FCALL1 , { NOQTEV, BLOCK }, 2 }, 
{ VDEC , { }, 0 }, 
{ DUMMY , { }, 0 }, 
{ FDECL , { }, 0 }, 
{ PRG2 , { }, 0 }, 
{ QAYTAR , { IDT, NOQTEV, }, 2 }, 
{ QAYTAR1 , { }, 0 }, 
{ NEQEDERKI , { BRK_SHERT, }, 1 }, 
{ NEQEDERKI1 , { }, 0 }, 
{ NEQEDERKI2 , { SIMPLE_OPER }, 1 }, 
{ DAVAMET , { NOQTEV, }, 1 }, 
{ DAYAN , { NOQTEV, }, 1 }, 
{ DAVAMET1 , { }, 0 }, 
{ DAYAN1 , { }, 0 }, 
{ SEC , { BRK_VAL, }, 1 }, 
{ SEC_OP , { }, 0 }, 
{ HAL , { NUMB, }, 1 }, 
{ HAL1 , {  SIMPLE_OPER  }, 1 }, 
{ HAL2 , {  CLSBLK, }, 1 }, 
{ HAL3 , { }, 0 }, 
{ SEC1 , { OPNBLK, }, 1 }, 
{ SUSMA , { COLON, }, 1 }, 
{ START , { }, 0 }, 
{ STRUKT , { }, 0 }, 
{ STRUKT1 , { }, 0 }, 
{ STRUKT2 , { }, 0 }, 
{ STRUKT3 , { }, 0 }, 
{ YNT1 , { }, 0 }, 
{ YNT2 , { }, 0 }, 
{ STRMEM , { }, 0 }, 
{ YNTS , { }, 0 }, 
{ SINIF , { }, 0 }, 
{ MEXSUSI , { }, 0 }, 
{ UMUMI , { }, 0 }, 
{ QORUNAN , { }, 0 }, 
{ SINIF_HEAD , { }, 0 }, 
{ SINIF_HEAD_START , { }, 0 }, 
{ SINIF_BODY , { }, 0 }, 
{ SINIF_DECL , { }, 0 }, 
{ SINIF_TYPE , { }, 0 }, 
{ YENI_TIP , { }, 0 }, 
{ SNMEM , { }, 0 }, 
{ INIT_DOVR , { }, 0 }, 
{ CHECK_DOVR , { }, 0 }, 
{ STEP_DOVR , { }, 0 }, 
{ NEQ_TOP , { }, 0 }, 
{ SUS1 , {  SIMPLE_OPER   }, 1 }, 
{ HAL1S , {  SIMPLE_OPER  }, 1 }, 
{ FARGS , { }, 0 }, 
{ FPARM , { }, 0 }, 
{ FCALL_BEG , { }, 0 }, 
{ PUT_RET_ADDR , { }, 0 }, 
{ IDT_ADRS , { }, 0 }, 
{ CRG1_ADRS , { }, 0 }, 
{ CRG2_ADRS , { }, 0 }, 
{ CRG1_VAL , { }, 0 }, 
{ CRG2_VAL , { }, 0 }, 
{ IDT_VAL , { }, 0 }, 
{ IDT_OFST , { }, 0 }, 
{ CRG1_OFST , { }, 0 }, 
{ CRG2_OFST , { }, 0 }, 
{ STRMEM_VAL , { }, 0 }, 
{ CAPET_NUMB , { }, 0 }, 
{ CAPET_FLOAT , { }, 0 }, 
{ CAPET_CHR , { }, 0 }, 
{ CAPET_STR , { }, 0 }, 
{ CAPET_IDT , { }, 0 }, 
{ CAPET_CRG1 , { }, 0 }, 
{ CAPET_CRG2 , { }, 0 }, 
{ CAPET_STRMEM , { }, 0 }, 
{ CHR_ADRS , { }, 0 }, 
{ STR_ADRS , { }, 0 }, 
{ CAPET_EXPR , { }, 0 }, 
{ DAXILET_IDT , { }, 0 }, 
{ FARGS_NUMB , { }, 0 }, 
{ FARGS_FLOAT , { }, 0 }, 
{ FARGS_CHR , { }, 0 }, 
{ FARGS_STR , { }, 0 }, 
{ FARGS_IDT_VAL , { }, 0 }, 
{ FARGS_CRG1_VAL , { }, 0 }, 
{ FARGS_CRG2_VAL , { }, 0 }, 
{ FARGS_STRMEM_VAL , { }, 0 }, 
{ FARGS_EXPR_VAL , { }, 0 }, 
{ FPARM_IDT_VAL , { }, 0 }, 
{ POP_OBSTK , { }, 0 }, 
{ GLBMT , { }, 0 }, 
{ FREE_SEC_DYN_STK , { }, 0 }, 
{ KVK , { }, 0 }, 
{ KVK1 , { }, 0 }, 
{ POP_FNSTK , { }, 0 }, 
{ GET_FUNC_RET_RES , { }, 0 }, 
{ PUT_FUNC_RET_RES , { }, 0 }, 
{ KOD_WITH_VAR , { }, 0 }, 
{ KOD_FUNK , {  }, 0 }, 
{ TEXT , {  }, 0 }, 
{ STANDART , { }, 0 }, 
{ STANDART_FUNK , { }, 0 }, 
{ KVADRAT_KOK , { }, 0 }, 
{ STEKE_QOY , { }, 0 }, 
{ STEKE_QOY_STD , { }, 0 }, 
{ STEKDEN_GOTUR , { }, 0 }, 
{ STEKDEN_GOTUR_STD , { }, 0 }, 
{ SAY , { BRK_VAL, BRK_SEQ, }, 2 }, 
{ SAY_TIP_1 , { SIMPLE_OPER }, 1 }, 
{ CHECK_SAY_TIP_1 , { }, 0 }, 
{ STEP_SAY_TIP_1 , { }, 0 }, 
{ YNT1_FUNC_ARGS , { }, 0 }, 
{ SAY_TIP_2 , { }, 0 }, 
{ SAY_TIP_3 , { }, 0 }, 
{ CHECK_SAY_TIP_2 , { }, 0 }, 
{ STEP_SAY_TIP_2 , { }, 0 }, 
{ CHECK_SAY_TIP_3 , { }, 0 }, 
{ STEP_SAY_TIP_3 , { }, 0 }, 
{ INIT_SAY_TIP_3 , { }, 0 }, 
{ INIT_SAY_TIP_2 , { }, 0 }, 
{ INCREMENT , { NOQTEV,  IDT }, 2 }, 
{ DECREMENT , { NOQTEV,  IDT }, 2 }, 
{ INCREMENT_OPR , { }, 0 }, 
{ DECREMENT_OPR , { }, 0 }, 
{ DAXIL_INSIDE , { }, 0 }, 
{ CAPET_INSIDE , { }, 0 }, 
{ EGER_INSIDE , { }, 0 }, 
{ ARRAY_INDEX , { }, 0 }, 
{ FCALL_VDEC , { }, 0 }, 
{ SHERT_RIGHT , { }, 0 }, 
{ ASGN_RIGHT , { }, 0 }, 
{ SAY_INSIDE , { }, 0 }, 
{ FUNKSIYA_ELAN , { }, 0 }, 
{ BLOCK_INSIDE , { }, 0 }, 
{ SINIF_INSIDE , { }, 0 }, 
{ FREE_CONTEXT , { }, 0 }, 
{ OPERATOR , { }, 0 }, 
{ SIMPLE_OPER , {  YOXSA,  CLSBLK }, 2 }, 
{ EGER_OPER , { }, 0 }, 
{ EGER_YOXSA , { }, 0 }, 
{ EGER_YOXSA_OPER , { }, 0 }, 
{ NEQEDERKI_OPER , { }, 0 }, 
{ SECIM_OPER , { }, 0 }, 
{ KOD_PART , {  CLSBLK, }, 1 }, 
{ SAY_OPER , { }, 0 }, 
{ COMP_OPER , {  YOXSA,  CLSBLK }, 2 }, 
{ BRK_VAL , { POSSIG, NOQTEV,  VERGUL, GRT,  CLSBRK}, 5 }, 
{ ARYBRK_VAL , { }, 0 }, 
{ BRK_SHERT , { VE,  CLSBRK, }, 2 }, 
{ SEQ , { NOQTEV,  VERGUL,  CLSBRK, }, 3 }, 
{ BRK_SEQ , { CLSBRK, }, 1 }, 
{ BRK_EMP , { CLSBRK, }, 1 }


};

// 293 - 16

struct follow {
	int f1; // first
	int f2; // second 
};

int follow_set_len = 2011;

struct follow follow_set[] = {

{ FUNKSIYA, FCALL1 }, 
{ FCALL1, BLOCK }, 
{ FUNK, FUNK }, 
{ FUNK, KOD_PART }, 
{ FUNK, SIMPLE_OPER }, 
{ FUNK, COMP_OPER }, 
{ FUNK, BLOCK }, 
{ FUNK, KOD_FUNK }, 
{ KOD_PART, FUNK }, 
{ KOD_PART, KOD_PART }, 
{ KOD_PART, SIMPLE_OPER }, 
{ KOD_PART, COMP_OPER }, 
{ KOD_PART, BLOCK }, 
{ KOD_PART, KOD_FUNK }, 
{ SIMPLE_OPER, FUNK }, 
{ SIMPLE_OPER, KOD_PART }, 
{ SIMPLE_OPER, SIMPLE_OPER }, 
{ SIMPLE_OPER, COMP_OPER }, 
{ SIMPLE_OPER, BLOCK }, 
{ SIMPLE_OPER, KOD_FUNK }, 
{ COMP_OPER, FUNK }, 
{ COMP_OPER, KOD_PART }, 
{ COMP_OPER, SIMPLE_OPER }, 
{ COMP_OPER, COMP_OPER }, 
{ COMP_OPER, BLOCK }, 
{ COMP_OPER, KOD_FUNK }, 
{ BLOCK, FUNK }, 
{ BLOCK, KOD_PART }, 
{ BLOCK, SIMPLE_OPER }, 
{ BLOCK, COMP_OPER }, 
{ BLOCK, BLOCK }, 
{ BLOCK, KOD_FUNK }, 
{ KOD_FUNK, FUNK }, 
{ KOD_FUNK, KOD_PART }, 
{ KOD_FUNK, SIMPLE_OPER }, 
{ KOD_FUNK, COMP_OPER }, 
{ KOD_FUNK, BLOCK }, 
{ KOD_FUNK, KOD_FUNK }, 
{ OPNBLK, KOD_PART }, 
{ KOD_PART, CLSBLK }, 
{ OPNBLK, SIMPLE_OPER }, 
{ SIMPLE_OPER, CLSBLK }, 
{ OPNBLK, COMP_OPER }, 
{ COMP_OPER, CLSBLK }, 
{ OPNBLK, BLOCK }, 
{ BLOCK, CLSBLK }, 
{ OPNBLK, CLSBLK }, 
{ SIMPLE_OPER, SIMPLE_OPER }, 
{ SIMPLE_OPER, COMP_OPER }, 
{ SIMPLE_OPER, BLOCK }, 
{ SIMPLE_OPER, KOD_PART }, 
{ COMP_OPER, SIMPLE_OPER }, 
{ COMP_OPER, COMP_OPER }, 
{ COMP_OPER, BLOCK }, 
{ COMP_OPER, KOD_PART }, 
{ BLOCK, SIMPLE_OPER }, 
{ BLOCK, COMP_OPER }, 
{ BLOCK, BLOCK }, 
{ BLOCK, KOD_PART }, 
{ KOD_PART, SIMPLE_OPER }, 
{ KOD_PART, COMP_OPER }, 
{ KOD_PART, BLOCK }, 
{ KOD_PART, KOD_PART }, 
{ EGER_EXP2, SIMPLE_OPER }, 
{ SIMPLE_OPER, YOXSA }, 
{ YOXSA, SIMPLE_OPER }, 
{ EGER_EXP2, SIMPLE_OPER }, 
{ SIMPLE_OPER, YOXSA }, 
{ YOXSA, COMP_OPER }, 
{ EGER_EXP2, SIMPLE_OPER }, 
{ SIMPLE_OPER, YOXSA }, 
{ YOXSA, BLOCK }, 
{ EGER_EXP2, COMP_OPER }, 
{ COMP_OPER, YOXSA }, 
{ YOXSA, SIMPLE_OPER }, 
{ EGER_EXP2, COMP_OPER }, 
{ COMP_OPER, YOXSA }, 
{ YOXSA, COMP_OPER }, 
{ EGER_EXP2, COMP_OPER }, 
{ COMP_OPER, YOXSA }, 
{ YOXSA, BLOCK }, 
{ EGER_EXP2, BLOCK }, 
{ BLOCK, YOXSA }, 
{ YOXSA, SIMPLE_OPER }, 
{ EGER_EXP2, BLOCK }, 
{ BLOCK, YOXSA }, 
{ YOXSA, COMP_OPER }, 
{ EGER_EXP2, BLOCK }, 
{ BLOCK, YOXSA }, 
{ YOXSA, BLOCK }, 
{ EGER_EXP2, SIMPLE_OPER }, 
{ SIMPLE_OPER, YOXSA }, 
{ EGER_EXP2, COMP_OPER }, 
{ COMP_OPER, YOXSA }, 
{ EGER_EXP2, BLOCK }, 
{ BLOCK, YOXSA }, 
{ EGER_EXP2, SIMPLE_OPER }, 
{ SIMPLE_OPER, YOXSA_OPER }, 
{ EGER_EXP2, COMP_OPER }, 
{ COMP_OPER, YOXSA_OPER }, 
{ EGER_EXP2, BLOCK }, 
{ BLOCK, YOXSA_OPER }, 
{ EGER_YOXSA, SIMPLE_OPER }, 
{ EGER_YOXSA, COMP_OPER }, 
{ EGER_YOXSA, BLOCK }, 
{ YOXSA, SIMPLE_OPER }, 
{ YOXSA, COMP_OPER }, 
{ YOXSA, BLOCK }, 
{ EGER_EXP2, SIMPLE_OPER }, 
{ EGER_EXP2, COMP_OPER }, 
{ EGER_EXP2, BLOCK }, 
{ NEQEDERKI2, SIMPLE_OPER }, 
{ NEQEDERKI2, COMP_OPER }, 
{ NEQEDERKI2, BLOCK }, 
{ SEC1, OPNBLK }, 
{ OPNBLK, HAL2 }, 
{ HAL2, CLSBLK }, 
{ SAY_TIP_1, SIMPLE_OPER }, 
{ SAY_TIP_1, COMP_OPER }, 
{ SAY_TIP_1, BLOCK }, 
{ NEQEDERKI, BRK_SHERT }, 
{ SEC, BRK_VAL }, 
{ EGER, BRK_SHERT }, 
{ DAVAMET, NOQTEV }, 
{ DAYAN, NOQTEV }, 
{ SAY, BRK_VAL }, 
{ SAY, BRK_SEQ }, 
{ IDT, ASGN }, 
{ ASGN, IDT }, 
{ IDT, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, CRG1 }, 
{ CRG1, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, CRG2 }, 
{ CRG2, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, NUMB }, 
{ NUMB, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, CHR }, 
{ CHR, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, FLOAT }, 
{ FLOAT, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, EXPR }, 
{ EXPR, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, STR }, 
{ STR, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, FCALL1 }, 
{ FCALL1, NOQTEV }, 
{ IDT, ASGN }, 
{ ASGN, BRK_VAL }, 
{ BRK_VAL, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, IDT }, 
{ IDT, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, CRG1 }, 
{ CRG1, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, CRG2 }, 
{ CRG2, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, NUMB }, 
{ NUMB, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, CHR }, 
{ CHR, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, FLOAT }, 
{ FLOAT, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, EXPR }, 
{ EXPR, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, STR }, 
{ STR, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, FCALL1 }, 
{ FCALL1, NOQTEV }, 
{ CRG1, ASGN }, 
{ ASGN, BRK_VAL }, 
{ BRK_VAL, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, IDT }, 
{ IDT, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, CRG1 }, 
{ CRG1, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, CRG2 }, 
{ CRG2, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, NUMB }, 
{ NUMB, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, CHR }, 
{ CHR, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, FLOAT }, 
{ FLOAT, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, EXPR }, 
{ EXPR, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, STR }, 
{ STR, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, FCALL1 }, 
{ FCALL1, NOQTEV }, 
{ CRG2, ASGN }, 
{ ASGN, BRK_VAL }, 
{ BRK_VAL, NOQTEV }, 
{ HAL, NUMB }, 
{ NUMB, COLON }, 
{ HAL, CHR }, 
{ CHR, COLON }, 
{ TAM, IDT }, 
{ TAM, CRG1 }, 
{ TAM, CRG2 }, 
{ TAM, SEQ }, 
{ VDEC, NOQTEV }, 
{ SUSMA, COLON }, 
{ HAL1, HAL1 }, 
{ HAL1, HAL1S }, 
{ HAL1S, HAL1 }, 
{ HAL1S, HAL1S }, 
{ HAL1, KOD_PART }, 
{ HAL1, SIMPLE_OPER }, 
{ HAL1, COMP_OPER }, 
{ HAL1, BLOCK }, 
{ HAL1S, KOD_PART }, 
{ HAL1S, SIMPLE_OPER }, 
{ HAL1S, COMP_OPER }, 
{ HAL1S, BLOCK }, 
{ SUS1, KOD_PART }, 
{ SUS1, SIMPLE_OPER }, 
{ SUS1, COMP_OPER }, 
{ SUS1, BLOCK }, 
{ HAL2, HAL2 }, 
{ HAL2, KOD_PART }, 
{ HAL2, SIMPLE_OPER }, 
{ HAL2, COMP_OPER }, 
{ HAL2, BLOCK }, 
{ OPNBRK, CLSBRK }, 
{ TEXT, TEXT }, 
{ TEXT, KOD_FUNK }, 
{ TEXT, FUNK }, 
{ TEXT, KOD_PART }, 
{ TEXT, SIMPLE_OPER }, 
{ TEXT, COMP_OPER }, 
{ TEXT, BLOCK }, 
{ KOD_FUNK, TEXT }, 
{ KOD_FUNK, KOD_FUNK }, 
{ KOD_FUNK, FUNK }, 
{ KOD_FUNK, KOD_PART }, 
{ KOD_FUNK, SIMPLE_OPER }, 
{ KOD_FUNK, COMP_OPER }, 
{ KOD_FUNK, BLOCK }, 
{ FUNK, TEXT }, 
{ FUNK, KOD_FUNK }, 
{ FUNK, FUNK }, 
{ FUNK, KOD_PART }, 
{ FUNK, SIMPLE_OPER }, 
{ FUNK, COMP_OPER }, 
{ FUNK, BLOCK }, 
{ KOD_PART, TEXT }, 
{ KOD_PART, KOD_FUNK }, 
{ KOD_PART, FUNK }, 
{ KOD_PART, KOD_PART }, 
{ KOD_PART, SIMPLE_OPER }, 
{ KOD_PART, COMP_OPER }, 
{ KOD_PART, BLOCK }, 
{ SIMPLE_OPER, TEXT }, 
{ SIMPLE_OPER, KOD_FUNK }, 
{ SIMPLE_OPER, FUNK }, 
{ SIMPLE_OPER, KOD_PART }, 
{ SIMPLE_OPER, SIMPLE_OPER }, 
{ SIMPLE_OPER, COMP_OPER }, 
{ SIMPLE_OPER, BLOCK }, 
{ COMP_OPER, TEXT }, 
{ COMP_OPER, KOD_FUNK }, 
{ COMP_OPER, FUNK }, 
{ COMP_OPER, KOD_PART }, 
{ COMP_OPER, SIMPLE_OPER }, 
{ COMP_OPER, COMP_OPER }, 
{ COMP_OPER, BLOCK }, 
{ BLOCK, TEXT }, 
{ BLOCK, KOD_FUNK }, 
{ BLOCK, FUNK }, 
{ BLOCK, KOD_PART }, 
{ BLOCK, SIMPLE_OPER }, 
{ BLOCK, COMP_OPER }, 
{ BLOCK, BLOCK }, 
{ FCALL1, NOQTEV }, 
{ SHERT, VE }, 
{ VE, SHERT }, 
{ BRK_SHERT, VE }, 
{ VE, SHERT }, 
{ SHERT, VEYA }, 
{ VEYA, SHERT }, 
{ BRK_SHERT, VEYA }, 
{ VEYA, SHERT }, 
{ SHERT, VE }, 
{ VE, BRK_SHERT }, 
{ BRK_SHERT, VE }, 
{ VE, BRK_SHERT }, 
{ SHERT, VEYA }, 
{ VEYA, BRK_SHERT }, 
{ BRK_SHERT, VEYA }, 
{ VEYA, BRK_SHERT }, 
{ IDT, VERGUL }, 
{ VERGUL, IDT }, 
{ IDT, VERGUL }, 
{ VERGUL, CRG1 }, 
{ IDT, VERGUL }, 
{ VERGUL, CRG2 }, 
{ IDT, VERGUL }, 
{ VERGUL, NUMB }, 
{ IDT, VERGUL }, 
{ VERGUL, CHR }, 
{ IDT, VERGUL }, 
{ VERGUL, FLOAT }, 
{ IDT, VERGUL }, 
{ VERGUL, STR }, 
{ IDT, VERGUL }, 
{ VERGUL, EXPR }, 
{ IDT, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ IDT, VERGUL }, 
{ VERGUL, SEQ }, 
{ CRG1, VERGUL }, 
{ VERGUL, IDT }, 
{ CRG1, VERGUL }, 
{ VERGUL, CRG1 }, 
{ CRG1, VERGUL }, 
{ VERGUL, CRG2 }, 
{ CRG1, VERGUL }, 
{ VERGUL, NUMB }, 
{ CRG1, VERGUL }, 
{ VERGUL, CHR }, 
{ CRG1, VERGUL }, 
{ VERGUL, FLOAT }, 
{ CRG1, VERGUL }, 
{ VERGUL, STR }, 
{ CRG1, VERGUL }, 
{ VERGUL, EXPR }, 
{ CRG1, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ CRG1, VERGUL }, 
{ VERGUL, SEQ }, 
{ CRG2, VERGUL }, 
{ VERGUL, IDT }, 
{ CRG2, VERGUL }, 
{ VERGUL, CRG1 }, 
{ CRG2, VERGUL }, 
{ VERGUL, CRG2 }, 
{ CRG2, VERGUL }, 
{ VERGUL, NUMB }, 
{ CRG2, VERGUL }, 
{ VERGUL, CHR }, 
{ CRG2, VERGUL }, 
{ VERGUL, FLOAT }, 
{ CRG2, VERGUL }, 
{ VERGUL, STR }, 
{ CRG2, VERGUL }, 
{ VERGUL, EXPR }, 
{ CRG2, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ CRG2, VERGUL }, 
{ VERGUL, SEQ }, 
{ NUMB, VERGUL }, 
{ VERGUL, IDT }, 
{ NUMB, VERGUL }, 
{ VERGUL, CRG1 }, 
{ NUMB, VERGUL }, 
{ VERGUL, CRG2 }, 
{ NUMB, VERGUL }, 
{ VERGUL, NUMB }, 
{ NUMB, VERGUL }, 
{ VERGUL, CHR }, 
{ NUMB, VERGUL }, 
{ VERGUL, FLOAT }, 
{ NUMB, VERGUL }, 
{ VERGUL, STR }, 
{ NUMB, VERGUL }, 
{ VERGUL, EXPR }, 
{ NUMB, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ NUMB, VERGUL }, 
{ VERGUL, SEQ }, 
{ CHR, VERGUL }, 
{ VERGUL, IDT }, 
{ CHR, VERGUL }, 
{ VERGUL, CRG1 }, 
{ CHR, VERGUL }, 
{ VERGUL, CRG2 }, 
{ CHR, VERGUL }, 
{ VERGUL, NUMB }, 
{ CHR, VERGUL }, 
{ VERGUL, CHR }, 
{ CHR, VERGUL }, 
{ VERGUL, FLOAT }, 
{ CHR, VERGUL }, 
{ VERGUL, STR }, 
{ CHR, VERGUL }, 
{ VERGUL, EXPR }, 
{ CHR, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ CHR, VERGUL }, 
{ VERGUL, SEQ }, 
{ FLOAT, VERGUL }, 
{ VERGUL, IDT }, 
{ FLOAT, VERGUL }, 
{ VERGUL, CRG1 }, 
{ FLOAT, VERGUL }, 
{ VERGUL, CRG2 }, 
{ FLOAT, VERGUL }, 
{ VERGUL, NUMB }, 
{ FLOAT, VERGUL }, 
{ VERGUL, CHR }, 
{ FLOAT, VERGUL }, 
{ VERGUL, FLOAT }, 
{ FLOAT, VERGUL }, 
{ VERGUL, STR }, 
{ FLOAT, VERGUL }, 
{ VERGUL, EXPR }, 
{ FLOAT, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ FLOAT, VERGUL }, 
{ VERGUL, SEQ }, 
{ STR, VERGUL }, 
{ VERGUL, IDT }, 
{ STR, VERGUL }, 
{ VERGUL, CRG1 }, 
{ STR, VERGUL }, 
{ VERGUL, CRG2 }, 
{ STR, VERGUL }, 
{ VERGUL, NUMB }, 
{ STR, VERGUL }, 
{ VERGUL, CHR }, 
{ STR, VERGUL }, 
{ VERGUL, FLOAT }, 
{ STR, VERGUL }, 
{ VERGUL, STR }, 
{ STR, VERGUL }, 
{ VERGUL, EXPR }, 
{ STR, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ STR, VERGUL }, 
{ VERGUL, SEQ }, 
{ EXPR, VERGUL }, 
{ VERGUL, IDT }, 
{ EXPR, VERGUL }, 
{ VERGUL, CRG1 }, 
{ EXPR, VERGUL }, 
{ VERGUL, CRG2 }, 
{ EXPR, VERGUL }, 
{ VERGUL, NUMB }, 
{ EXPR, VERGUL }, 
{ VERGUL, CHR }, 
{ EXPR, VERGUL }, 
{ VERGUL, FLOAT }, 
{ EXPR, VERGUL }, 
{ VERGUL, STR }, 
{ EXPR, VERGUL }, 
{ VERGUL, EXPR }, 
{ EXPR, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ EXPR, VERGUL }, 
{ VERGUL, SEQ }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, IDT }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, CRG1 }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, CRG2 }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, NUMB }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, CHR }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, FLOAT }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, STR }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, EXPR }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ BRK_VAL, VERGUL }, 
{ VERGUL, SEQ }, 
{ SEQ, VERGUL }, 
{ VERGUL, IDT }, 
{ SEQ, VERGUL }, 
{ VERGUL, CRG1 }, 
{ SEQ, VERGUL }, 
{ VERGUL, CRG2 }, 
{ SEQ, VERGUL }, 
{ VERGUL, NUMB }, 
{ SEQ, VERGUL }, 
{ VERGUL, CHR }, 
{ SEQ, VERGUL }, 
{ VERGUL, FLOAT }, 
{ SEQ, VERGUL }, 
{ VERGUL, STR }, 
{ SEQ, VERGUL }, 
{ VERGUL, EXPR }, 
{ SEQ, VERGUL }, 
{ VERGUL, BRK_VAL }, 
{ SEQ, VERGUL }, 
{ VERGUL, SEQ }, 
{ IDT, GRT }, 
{ GRT, IDT }, 
{ IDT, GRT }, 
{ GRT, CRG1 }, 
{ IDT, GRT }, 
{ GRT, CRG2 }, 
{ IDT, GRT }, 
{ GRT, NUMB }, 
{ IDT, GRT }, 
{ GRT, CHR }, 
{ IDT, GRT }, 
{ GRT, FLOAT }, 
{ IDT, GRT }, 
{ GRT, EXPR }, 
{ IDT, GRT }, 
{ GRT, BRK_VAL }, 
{ IDT, LES }, 
{ LES, IDT }, 
{ IDT, LES }, 
{ LES, CRG1 }, 
{ IDT, LES }, 
{ LES, CRG2 }, 
{ IDT, LES }, 
{ LES, NUMB }, 
{ IDT, LES }, 
{ LES, CHR }, 
{ IDT, LES }, 
{ LES, FLOAT }, 
{ IDT, LES }, 
{ LES, EXPR }, 
{ IDT, LES }, 
{ LES, BRK_VAL }, 
{ IDT, BERABER }, 
{ BERABER, IDT }, 
{ IDT, BERABER }, 
{ BERABER, CRG1 }, 
{ IDT, BERABER }, 
{ BERABER, CRG2 }, 
{ IDT, BERABER }, 
{ BERABER, NUMB }, 
{ IDT, BERABER }, 
{ BERABER, CHR }, 
{ IDT, BERABER }, 
{ BERABER, FLOAT }, 
{ IDT, BERABER }, 
{ BERABER, EXPR }, 
{ IDT, BERABER }, 
{ BERABER, BRK_VAL }, 
{ IDT, FERQLI }, 
{ FERQLI, IDT }, 
{ IDT, FERQLI }, 
{ FERQLI, CRG1 }, 
{ IDT, FERQLI }, 
{ FERQLI, CRG2 }, 
{ IDT, FERQLI }, 
{ FERQLI, NUMB }, 
{ IDT, FERQLI }, 
{ FERQLI, CHR }, 
{ IDT, FERQLI }, 
{ FERQLI, FLOAT }, 
{ IDT, FERQLI }, 
{ FERQLI, EXPR }, 
{ IDT, FERQLI }, 
{ FERQLI, BRK_VAL }, 
{ IDT, GRTEQU }, 
{ GRTEQU, IDT }, 
{ IDT, GRTEQU }, 
{ GRTEQU, CRG1 }, 
{ IDT, GRTEQU }, 
{ GRTEQU, CRG2 }, 
{ IDT, GRTEQU }, 
{ GRTEQU, NUMB }, 
{ IDT, GRTEQU }, 
{ GRTEQU, CHR }, 
{ IDT, GRTEQU }, 
{ GRTEQU, FLOAT }, 
{ IDT, GRTEQU }, 
{ GRTEQU, EXPR }, 
{ IDT, GRTEQU }, 
{ GRTEQU, BRK_VAL }, 
{ IDT, LESEQU }, 
{ LESEQU, IDT }, 
{ IDT, LESEQU }, 
{ LESEQU, CRG1 }, 
{ IDT, LESEQU }, 
{ LESEQU, CRG2 }, 
{ IDT, LESEQU }, 
{ LESEQU, NUMB }, 
{ IDT, LESEQU }, 
{ LESEQU, CHR }, 
{ IDT, LESEQU }, 
{ LESEQU, FLOAT }, 
{ IDT, LESEQU }, 
{ LESEQU, EXPR }, 
{ IDT, LESEQU }, 
{ LESEQU, BRK_VAL }, 
{ CRG1, GRT }, 
{ GRT, IDT }, 
{ CRG1, GRT }, 
{ GRT, CRG1 }, 
{ CRG1, GRT }, 
{ GRT, CRG2 }, 
{ CRG1, GRT }, 
{ GRT, NUMB }, 
{ CRG1, GRT }, 
{ GRT, CHR }, 
{ CRG1, GRT }, 
{ GRT, FLOAT }, 
{ CRG1, GRT }, 
{ GRT, EXPR }, 
{ CRG1, GRT }, 
{ GRT, BRK_VAL }, 
{ CRG1, LES }, 
{ LES, IDT }, 
{ CRG1, LES }, 
{ LES, CRG1 }, 
{ CRG1, LES }, 
{ LES, CRG2 }, 
{ CRG1, LES }, 
{ LES, NUMB }, 
{ CRG1, LES }, 
{ LES, CHR }, 
{ CRG1, LES }, 
{ LES, FLOAT }, 
{ CRG1, LES }, 
{ LES, EXPR }, 
{ CRG1, LES }, 
{ LES, BRK_VAL }, 
{ CRG1, BERABER }, 
{ BERABER, IDT }, 
{ CRG1, BERABER }, 
{ BERABER, CRG1 }, 
{ CRG1, BERABER }, 
{ BERABER, CRG2 }, 
{ CRG1, BERABER }, 
{ BERABER, NUMB }, 
{ CRG1, BERABER }, 
{ BERABER, CHR }, 
{ CRG1, BERABER }, 
{ BERABER, FLOAT }, 
{ CRG1, BERABER }, 
{ BERABER, EXPR }, 
{ CRG1, BERABER }, 
{ BERABER, BRK_VAL }, 
{ CRG1, FERQLI }, 
{ FERQLI, IDT }, 
{ CRG1, FERQLI }, 
{ FERQLI, CRG1 }, 
{ CRG1, FERQLI }, 
{ FERQLI, CRG2 }, 
{ CRG1, FERQLI }, 
{ FERQLI, NUMB }, 
{ CRG1, FERQLI }, 
{ FERQLI, CHR }, 
{ CRG1, FERQLI }, 
{ FERQLI, FLOAT }, 
{ CRG1, FERQLI }, 
{ FERQLI, EXPR }, 
{ CRG1, FERQLI }, 
{ FERQLI, BRK_VAL }, 
{ CRG1, GRTEQU }, 
{ GRTEQU, IDT }, 
{ CRG1, GRTEQU }, 
{ GRTEQU, CRG1 }, 
{ CRG1, GRTEQU }, 
{ GRTEQU, CRG2 }, 
{ CRG1, GRTEQU }, 
{ GRTEQU, NUMB }, 
{ CRG1, GRTEQU }, 
{ GRTEQU, CHR }, 
{ CRG1, GRTEQU }, 
{ GRTEQU, FLOAT }, 
{ CRG1, GRTEQU }, 
{ GRTEQU, EXPR }, 
{ CRG1, GRTEQU }, 
{ GRTEQU, BRK_VAL }, 
{ CRG1, LESEQU }, 
{ LESEQU, IDT }, 
{ CRG1, LESEQU }, 
{ LESEQU, CRG1 }, 
{ CRG1, LESEQU }, 
{ LESEQU, CRG2 }, 
{ CRG1, LESEQU }, 
{ LESEQU, NUMB }, 
{ CRG1, LESEQU }, 
{ LESEQU, CHR }, 
{ CRG1, LESEQU }, 
{ LESEQU, FLOAT }, 
{ CRG1, LESEQU }, 
{ LESEQU, EXPR }, 
{ CRG1, LESEQU }, 
{ LESEQU, BRK_VAL }, 
{ CRG2, GRT }, 
{ GRT, IDT }, 
{ CRG2, GRT }, 
{ GRT, CRG1 }, 
{ CRG2, GRT }, 
{ GRT, CRG2 }, 
{ CRG2, GRT }, 
{ GRT, NUMB }, 
{ CRG2, GRT }, 
{ GRT, CHR }, 
{ CRG2, GRT }, 
{ GRT, FLOAT }, 
{ CRG2, GRT }, 
{ GRT, EXPR }, 
{ CRG2, GRT }, 
{ GRT, BRK_VAL }, 
{ CRG2, LES }, 
{ LES, IDT }, 
{ CRG2, LES }, 
{ LES, CRG1 }, 
{ CRG2, LES }, 
{ LES, CRG2 }, 
{ CRG2, LES }, 
{ LES, NUMB }, 
{ CRG2, LES }, 
{ LES, CHR }, 
{ CRG2, LES }, 
{ LES, FLOAT }, 
{ CRG2, LES }, 
{ LES, EXPR }, 
{ CRG2, LES }, 
{ LES, BRK_VAL }, 
{ CRG2, BERABER }, 
{ BERABER, IDT }, 
{ CRG2, BERABER }, 
{ BERABER, CRG1 }, 
{ CRG2, BERABER }, 
{ BERABER, CRG2 }, 
{ CRG2, BERABER }, 
{ BERABER, NUMB }, 
{ CRG2, BERABER }, 
{ BERABER, CHR }, 
{ CRG2, BERABER }, 
{ BERABER, FLOAT }, 
{ CRG2, BERABER }, 
{ BERABER, EXPR }, 
{ CRG2, BERABER }, 
{ BERABER, BRK_VAL }, 
{ CRG2, FERQLI }, 
{ FERQLI, IDT }, 
{ CRG2, FERQLI }, 
{ FERQLI, CRG1 }, 
{ CRG2, FERQLI }, 
{ FERQLI, CRG2 }, 
{ CRG2, FERQLI }, 
{ FERQLI, NUMB }, 
{ CRG2, FERQLI }, 
{ FERQLI, CHR }, 
{ CRG2, FERQLI }, 
{ FERQLI, FLOAT }, 
{ CRG2, FERQLI }, 
{ FERQLI, EXPR }, 
{ CRG2, FERQLI }, 
{ FERQLI, BRK_VAL }, 
{ CRG2, GRTEQU }, 
{ GRTEQU, IDT }, 
{ CRG2, GRTEQU }, 
{ GRTEQU, CRG1 }, 
{ CRG2, GRTEQU }, 
{ GRTEQU, CRG2 }, 
{ CRG2, GRTEQU }, 
{ GRTEQU, NUMB }, 
{ CRG2, GRTEQU }, 
{ GRTEQU, CHR }, 
{ CRG2, GRTEQU }, 
{ GRTEQU, FLOAT }, 
{ CRG2, GRTEQU }, 
{ GRTEQU, EXPR }, 
{ CRG2, GRTEQU }, 
{ GRTEQU, BRK_VAL }, 
{ CRG2, LESEQU }, 
{ LESEQU, IDT }, 
{ CRG2, LESEQU }, 
{ LESEQU, CRG1 }, 
{ CRG2, LESEQU }, 
{ LESEQU, CRG2 }, 
{ CRG2, LESEQU }, 
{ LESEQU, NUMB }, 
{ CRG2, LESEQU }, 
{ LESEQU, CHR }, 
{ CRG2, LESEQU }, 
{ LESEQU, FLOAT }, 
{ CRG2, LESEQU }, 
{ LESEQU, EXPR }, 
{ CRG2, LESEQU }, 
{ LESEQU, BRK_VAL }, 
{ NUMB, GRT }, 
{ GRT, IDT }, 
{ NUMB, GRT }, 
{ GRT, CRG1 }, 
{ NUMB, GRT }, 
{ GRT, CRG2 }, 
{ NUMB, GRT }, 
{ GRT, NUMB }, 
{ NUMB, GRT }, 
{ GRT, CHR }, 
{ NUMB, GRT }, 
{ GRT, FLOAT }, 
{ NUMB, GRT }, 
{ GRT, EXPR }, 
{ NUMB, GRT }, 
{ GRT, BRK_VAL }, 
{ NUMB, LES }, 
{ LES, IDT }, 
{ NUMB, LES }, 
{ LES, CRG1 }, 
{ NUMB, LES }, 
{ LES, CRG2 }, 
{ NUMB, LES }, 
{ LES, NUMB }, 
{ NUMB, LES }, 
{ LES, CHR }, 
{ NUMB, LES }, 
{ LES, FLOAT }, 
{ NUMB, LES }, 
{ LES, EXPR }, 
{ NUMB, LES }, 
{ LES, BRK_VAL }, 
{ NUMB, BERABER }, 
{ BERABER, IDT }, 
{ NUMB, BERABER }, 
{ BERABER, CRG1 }, 
{ NUMB, BERABER }, 
{ BERABER, CRG2 }, 
{ NUMB, BERABER }, 
{ BERABER, NUMB }, 
{ NUMB, BERABER }, 
{ BERABER, CHR }, 
{ NUMB, BERABER }, 
{ BERABER, FLOAT }, 
{ NUMB, BERABER }, 
{ BERABER, EXPR }, 
{ NUMB, BERABER }, 
{ BERABER, BRK_VAL }, 
{ NUMB, FERQLI }, 
{ FERQLI, IDT }, 
{ NUMB, FERQLI }, 
{ FERQLI, CRG1 }, 
{ NUMB, FERQLI }, 
{ FERQLI, CRG2 }, 
{ NUMB, FERQLI }, 
{ FERQLI, NUMB }, 
{ NUMB, FERQLI }, 
{ FERQLI, CHR }, 
{ NUMB, FERQLI }, 
{ FERQLI, FLOAT }, 
{ NUMB, FERQLI }, 
{ FERQLI, EXPR }, 
{ NUMB, FERQLI }, 
{ FERQLI, BRK_VAL }, 
{ NUMB, GRTEQU }, 
{ GRTEQU, IDT }, 
{ NUMB, GRTEQU }, 
{ GRTEQU, CRG1 }, 
{ NUMB, GRTEQU }, 
{ GRTEQU, CRG2 }, 
{ NUMB, GRTEQU }, 
{ GRTEQU, NUMB }, 
{ NUMB, GRTEQU }, 
{ GRTEQU, CHR }, 
{ NUMB, GRTEQU }, 
{ GRTEQU, FLOAT }, 
{ NUMB, GRTEQU }, 
{ GRTEQU, EXPR }, 
{ NUMB, GRTEQU }, 
{ GRTEQU, BRK_VAL }, 
{ NUMB, LESEQU }, 
{ LESEQU, IDT }, 
{ NUMB, LESEQU }, 
{ LESEQU, CRG1 }, 
{ NUMB, LESEQU }, 
{ LESEQU, CRG2 }, 
{ NUMB, LESEQU }, 
{ LESEQU, NUMB }, 
{ NUMB, LESEQU }, 
{ LESEQU, CHR }, 
{ NUMB, LESEQU }, 
{ LESEQU, FLOAT }, 
{ NUMB, LESEQU }, 
{ LESEQU, EXPR }, 
{ NUMB, LESEQU }, 
{ LESEQU, BRK_VAL }, 
{ CHR, GRT }, 
{ GRT, IDT }, 
{ CHR, GRT }, 
{ GRT, CRG1 }, 
{ CHR, GRT }, 
{ GRT, CRG2 }, 
{ CHR, GRT }, 
{ GRT, NUMB }, 
{ CHR, GRT }, 
{ GRT, CHR }, 
{ CHR, GRT }, 
{ GRT, FLOAT }, 
{ CHR, GRT }, 
{ GRT, EXPR }, 
{ CHR, GRT }, 
{ GRT, BRK_VAL }, 
{ CHR, LES }, 
{ LES, IDT }, 
{ CHR, LES }, 
{ LES, CRG1 }, 
{ CHR, LES }, 
{ LES, CRG2 }, 
{ CHR, LES }, 
{ LES, NUMB }, 
{ CHR, LES }, 
{ LES, CHR }, 
{ CHR, LES }, 
{ LES, FLOAT }, 
{ CHR, LES }, 
{ LES, EXPR }, 
{ CHR, LES }, 
{ LES, BRK_VAL }, 
{ CHR, BERABER }, 
{ BERABER, IDT }, 
{ CHR, BERABER }, 
{ BERABER, CRG1 }, 
{ CHR, BERABER }, 
{ BERABER, CRG2 }, 
{ CHR, BERABER }, 
{ BERABER, NUMB }, 
{ CHR, BERABER }, 
{ BERABER, CHR }, 
{ CHR, BERABER }, 
{ BERABER, FLOAT }, 
{ CHR, BERABER }, 
{ BERABER, EXPR }, 
{ CHR, BERABER }, 
{ BERABER, BRK_VAL }, 
{ CHR, FERQLI }, 
{ FERQLI, IDT }, 
{ CHR, FERQLI }, 
{ FERQLI, CRG1 }, 
{ CHR, FERQLI }, 
{ FERQLI, CRG2 }, 
{ CHR, FERQLI }, 
{ FERQLI, NUMB }, 
{ CHR, FERQLI }, 
{ FERQLI, CHR }, 
{ CHR, FERQLI }, 
{ FERQLI, FLOAT }, 
{ CHR, FERQLI }, 
{ FERQLI, EXPR }, 
{ CHR, FERQLI }, 
{ FERQLI, BRK_VAL }, 
{ CHR, GRTEQU }, 
{ GRTEQU, IDT }, 
{ CHR, GRTEQU }, 
{ GRTEQU, CRG1 }, 
{ CHR, GRTEQU }, 
{ GRTEQU, CRG2 }, 
{ CHR, GRTEQU }, 
{ GRTEQU, NUMB }, 
{ CHR, GRTEQU }, 
{ GRTEQU, CHR }, 
{ CHR, GRTEQU }, 
{ GRTEQU, FLOAT }, 
{ CHR, GRTEQU }, 
{ GRTEQU, EXPR }, 
{ CHR, GRTEQU }, 
{ GRTEQU, BRK_VAL }, 
{ CHR, LESEQU }, 
{ LESEQU, IDT }, 
{ CHR, LESEQU }, 
{ LESEQU, CRG1 }, 
{ CHR, LESEQU }, 
{ LESEQU, CRG2 }, 
{ CHR, LESEQU }, 
{ LESEQU, NUMB }, 
{ CHR, LESEQU }, 
{ LESEQU, CHR }, 
{ CHR, LESEQU }, 
{ LESEQU, FLOAT }, 
{ CHR, LESEQU }, 
{ LESEQU, EXPR }, 
{ CHR, LESEQU }, 
{ LESEQU, BRK_VAL }, 
{ FLOAT, GRT }, 
{ GRT, IDT }, 
{ FLOAT, GRT }, 
{ GRT, CRG1 }, 
{ FLOAT, GRT }, 
{ GRT, CRG2 }, 
{ FLOAT, GRT }, 
{ GRT, NUMB }, 
{ FLOAT, GRT }, 
{ GRT, CHR }, 
{ FLOAT, GRT }, 
{ GRT, FLOAT }, 
{ FLOAT, GRT }, 
{ GRT, EXPR }, 
{ FLOAT, GRT }, 
{ GRT, BRK_VAL }, 
{ FLOAT, LES }, 
{ LES, IDT }, 
{ FLOAT, LES }, 
{ LES, CRG1 }, 
{ FLOAT, LES }, 
{ LES, CRG2 }, 
{ FLOAT, LES }, 
{ LES, NUMB }, 
{ FLOAT, LES }, 
{ LES, CHR }, 
{ FLOAT, LES }, 
{ LES, FLOAT }, 
{ FLOAT, LES }, 
{ LES, EXPR }, 
{ FLOAT, LES }, 
{ LES, BRK_VAL }, 
{ FLOAT, BERABER }, 
{ BERABER, IDT }, 
{ FLOAT, BERABER }, 
{ BERABER, CRG1 }, 
{ FLOAT, BERABER }, 
{ BERABER, CRG2 }, 
{ FLOAT, BERABER }, 
{ BERABER, NUMB }, 
{ FLOAT, BERABER }, 
{ BERABER, CHR }, 
{ FLOAT, BERABER }, 
{ BERABER, FLOAT }, 
{ FLOAT, BERABER }, 
{ BERABER, EXPR }, 
{ FLOAT, BERABER }, 
{ BERABER, BRK_VAL }, 
{ FLOAT, FERQLI }, 
{ FERQLI, IDT }, 
{ FLOAT, FERQLI }, 
{ FERQLI, CRG1 }, 
{ FLOAT, FERQLI }, 
{ FERQLI, CRG2 }, 
{ FLOAT, FERQLI }, 
{ FERQLI, NUMB }, 
{ FLOAT, FERQLI }, 
{ FERQLI, CHR }, 
{ FLOAT, FERQLI }, 
{ FERQLI, FLOAT }, 
{ FLOAT, FERQLI }, 
{ FERQLI, EXPR }, 
{ FLOAT, FERQLI }, 
{ FERQLI, BRK_VAL }, 
{ FLOAT, GRTEQU }, 
{ GRTEQU, IDT }, 
{ FLOAT, GRTEQU }, 
{ GRTEQU, CRG1 }, 
{ FLOAT, GRTEQU }, 
{ GRTEQU, CRG2 }, 
{ FLOAT, GRTEQU }, 
{ GRTEQU, NUMB }, 
{ FLOAT, GRTEQU }, 
{ GRTEQU, CHR }, 
{ FLOAT, GRTEQU }, 
{ GRTEQU, FLOAT }, 
{ FLOAT, GRTEQU }, 
{ GRTEQU, EXPR }, 
{ FLOAT, GRTEQU }, 
{ GRTEQU, BRK_VAL }, 
{ FLOAT, LESEQU }, 
{ LESEQU, IDT }, 
{ FLOAT, LESEQU }, 
{ LESEQU, CRG1 }, 
{ FLOAT, LESEQU }, 
{ LESEQU, CRG2 }, 
{ FLOAT, LESEQU }, 
{ LESEQU, NUMB }, 
{ FLOAT, LESEQU }, 
{ LESEQU, CHR }, 
{ FLOAT, LESEQU }, 
{ LESEQU, FLOAT }, 
{ FLOAT, LESEQU }, 
{ LESEQU, EXPR }, 
{ FLOAT, LESEQU }, 
{ LESEQU, BRK_VAL }, 
{ EXPR, GRT }, 
{ GRT, IDT }, 
{ EXPR, GRT }, 
{ GRT, CRG1 }, 
{ EXPR, GRT }, 
{ GRT, CRG2 }, 
{ EXPR, GRT }, 
{ GRT, NUMB }, 
{ EXPR, GRT }, 
{ GRT, CHR }, 
{ EXPR, GRT }, 
{ GRT, FLOAT }, 
{ EXPR, GRT }, 
{ GRT, EXPR }, 
{ EXPR, GRT }, 
{ GRT, BRK_VAL }, 
{ EXPR, LES }, 
{ LES, IDT }, 
{ EXPR, LES }, 
{ LES, CRG1 }, 
{ EXPR, LES }, 
{ LES, CRG2 }, 
{ EXPR, LES }, 
{ LES, NUMB }, 
{ EXPR, LES }, 
{ LES, CHR }, 
{ EXPR, LES }, 
{ LES, FLOAT }, 
{ EXPR, LES }, 
{ LES, EXPR }, 
{ EXPR, LES }, 
{ LES, BRK_VAL }, 
{ EXPR, BERABER }, 
{ BERABER, IDT }, 
{ EXPR, BERABER }, 
{ BERABER, CRG1 }, 
{ EXPR, BERABER }, 
{ BERABER, CRG2 }, 
{ EXPR, BERABER }, 
{ BERABER, NUMB }, 
{ EXPR, BERABER }, 
{ BERABER, CHR }, 
{ EXPR, BERABER }, 
{ BERABER, FLOAT }, 
{ EXPR, BERABER }, 
{ BERABER, EXPR }, 
{ EXPR, BERABER }, 
{ BERABER, BRK_VAL }, 
{ EXPR, FERQLI }, 
{ FERQLI, IDT }, 
{ EXPR, FERQLI }, 
{ FERQLI, CRG1 }, 
{ EXPR, FERQLI }, 
{ FERQLI, CRG2 }, 
{ EXPR, FERQLI }, 
{ FERQLI, NUMB }, 
{ EXPR, FERQLI }, 
{ FERQLI, CHR }, 
{ EXPR, FERQLI }, 
{ FERQLI, FLOAT }, 
{ EXPR, FERQLI }, 
{ FERQLI, EXPR }, 
{ EXPR, FERQLI }, 
{ FERQLI, BRK_VAL }, 
{ EXPR, GRTEQU }, 
{ GRTEQU, IDT }, 
{ EXPR, GRTEQU }, 
{ GRTEQU, CRG1 }, 
{ EXPR, GRTEQU }, 
{ GRTEQU, CRG2 }, 
{ EXPR, GRTEQU }, 
{ GRTEQU, NUMB }, 
{ EXPR, GRTEQU }, 
{ GRTEQU, CHR }, 
{ EXPR, GRTEQU }, 
{ GRTEQU, FLOAT }, 
{ EXPR, GRTEQU }, 
{ GRTEQU, EXPR }, 
{ EXPR, GRTEQU }, 
{ GRTEQU, BRK_VAL }, 
{ EXPR, LESEQU }, 
{ LESEQU, IDT }, 
{ EXPR, LESEQU }, 
{ LESEQU, CRG1 }, 
{ EXPR, LESEQU }, 
{ LESEQU, CRG2 }, 
{ EXPR, LESEQU }, 
{ LESEQU, NUMB }, 
{ EXPR, LESEQU }, 
{ LESEQU, CHR }, 
{ EXPR, LESEQU }, 
{ LESEQU, FLOAT }, 
{ EXPR, LESEQU }, 
{ LESEQU, EXPR }, 
{ EXPR, LESEQU }, 
{ LESEQU, BRK_VAL }, 
{ BRK_VAL, GRT }, 
{ GRT, IDT }, 
{ BRK_VAL, GRT }, 
{ GRT, CRG1 }, 
{ BRK_VAL, GRT }, 
{ GRT, CRG2 }, 
{ BRK_VAL, GRT }, 
{ GRT, NUMB }, 
{ BRK_VAL, GRT }, 
{ GRT, CHR }, 
{ BRK_VAL, GRT }, 
{ GRT, FLOAT }, 
{ BRK_VAL, GRT }, 
{ GRT, EXPR }, 
{ BRK_VAL, GRT }, 
{ GRT, BRK_VAL }, 
{ BRK_VAL, LES }, 
{ LES, IDT }, 
{ BRK_VAL, LES }, 
{ LES, CRG1 }, 
{ BRK_VAL, LES }, 
{ LES, CRG2 }, 
{ BRK_VAL, LES }, 
{ LES, NUMB }, 
{ BRK_VAL, LES }, 
{ LES, CHR }, 
{ BRK_VAL, LES }, 
{ LES, FLOAT }, 
{ BRK_VAL, LES }, 
{ LES, EXPR }, 
{ BRK_VAL, LES }, 
{ LES, BRK_VAL }, 
{ BRK_VAL, BERABER }, 
{ BERABER, IDT }, 
{ BRK_VAL, BERABER }, 
{ BERABER, CRG1 }, 
{ BRK_VAL, BERABER }, 
{ BERABER, CRG2 }, 
{ BRK_VAL, BERABER }, 
{ BERABER, NUMB }, 
{ BRK_VAL, BERABER }, 
{ BERABER, CHR }, 
{ BRK_VAL, BERABER }, 
{ BERABER, FLOAT }, 
{ BRK_VAL, BERABER }, 
{ BERABER, EXPR }, 
{ BRK_VAL, BERABER }, 
{ BERABER, BRK_VAL }, 
{ BRK_VAL, FERQLI }, 
{ FERQLI, IDT }, 
{ BRK_VAL, FERQLI }, 
{ FERQLI, CRG1 }, 
{ BRK_VAL, FERQLI }, 
{ FERQLI, CRG2 }, 
{ BRK_VAL, FERQLI }, 
{ FERQLI, NUMB }, 
{ BRK_VAL, FERQLI }, 
{ FERQLI, CHR }, 
{ BRK_VAL, FERQLI }, 
{ FERQLI, FLOAT }, 
{ BRK_VAL, FERQLI }, 
{ FERQLI, EXPR }, 
{ BRK_VAL, FERQLI }, 
{ FERQLI, BRK_VAL }, 
{ BRK_VAL, GRTEQU }, 
{ GRTEQU, IDT }, 
{ BRK_VAL, GRTEQU }, 
{ GRTEQU, CRG1 }, 
{ BRK_VAL, GRTEQU }, 
{ GRTEQU, CRG2 }, 
{ BRK_VAL, GRTEQU }, 
{ GRTEQU, NUMB }, 
{ BRK_VAL, GRTEQU }, 
{ GRTEQU, CHR }, 
{ BRK_VAL, GRTEQU }, 
{ GRTEQU, FLOAT }, 
{ BRK_VAL, GRTEQU }, 
{ GRTEQU, EXPR }, 
{ BRK_VAL, GRTEQU }, 
{ GRTEQU, BRK_VAL }, 
{ BRK_VAL, LESEQU }, 
{ LESEQU, IDT }, 
{ BRK_VAL, LESEQU }, 
{ LESEQU, CRG1 }, 
{ BRK_VAL, LESEQU }, 
{ LESEQU, CRG2 }, 
{ BRK_VAL, LESEQU }, 
{ LESEQU, NUMB }, 
{ BRK_VAL, LESEQU }, 
{ LESEQU, CHR }, 
{ BRK_VAL, LESEQU }, 
{ LESEQU, FLOAT }, 
{ BRK_VAL, LESEQU }, 
{ LESEQU, EXPR }, 
{ BRK_VAL, LESEQU }, 
{ LESEQU, BRK_VAL }, 
{ OPNBRK, IDT }, 
{ IDT, CLSBRK }, 
{ OPNBRK, CRG1 }, 
{ CRG1, CLSBRK }, 
{ OPNBRK, CRG2 }, 
{ CRG2, CLSBRK }, 
{ OPNBRK, NUMB }, 
{ NUMB, CLSBRK }, 
{ OPNBRK, FLOAT }, 
{ FLOAT, CLSBRK }, 
{ OPNBRK, CHR }, 
{ CHR, CLSBRK }, 
{ OPNBRK, EXPR }, 
{ EXPR, CLSBRK }, 
{ OPNBRK, STR }, 
{ STR, CLSBRK }, 
{ OPNBRK, BRK_VAL }, 
{ BRK_VAL, CLSBRK }, 
{ OPNBRK, SHERT }, 
{ SHERT, CLSBRK }, 
{ OPNBRK, BRK_SHERT }, 
{ BRK_SHERT, CLSBRK }, 
{ OPNBRK, SEQ }, 
{ SEQ, CLSBRK }, 
{ OPNBRK, BRK_SEQ }, 
{ BRK_SEQ, CLSBRK }, 
{ OPNBRK, BRK_EMP }, 
{ BRK_EMP, CLSBRK }, 
{ ARYOPN, IDT }, 
{ IDT, ARYCLS }, 
{ ARYOPN, CRG1 }, 
{ CRG1, ARYCLS }, 
{ ARYOPN, CRG2 }, 
{ CRG2, ARYCLS }, 
{ ARYOPN, NUMB }, 
{ NUMB, ARYCLS }, 
{ ARYOPN, FLOAT }, 
{ FLOAT, ARYCLS }, 
{ ARYOPN, CHR }, 
{ CHR, ARYCLS }, 
{ ARYOPN, EXPR }, 
{ EXPR, ARYCLS }, 
{ CRG1, ARYBRK_VAL }, 
{ IDT, ARYBRK_VAL }, 
{ IDT, DECREMENT }, 
{ DECREMENT, NOQTEV }, 
{ CRG1, DECREMENT }, 
{ DECREMENT, NOQTEV }, 
{ CRG2, DECREMENT }, 
{ DECREMENT, NOQTEV }, 
{ DECREMENT, IDT }, 
{ IDT, NOQTEV }, 
{ DECREMENT, CRG1 }, 
{ CRG1, NOQTEV }, 
{ DECREMENT, CRG2 }, 
{ CRG2, NOQTEV }, 
{ IDT, INCREMENT }, 
{ INCREMENT, NOQTEV }, 
{ CRG1, INCREMENT }, 
{ INCREMENT, NOQTEV }, 
{ CRG2, INCREMENT }, 
{ INCREMENT, NOQTEV }, 
{ INCREMENT, IDT }, 
{ IDT, NOQTEV }, 
{ INCREMENT, CRG1 }, 
{ CRG1, NOQTEV }, 
{ INCREMENT, CRG2 }, 
{ CRG2, NOQTEV }, 
{ QAYTAR, IDT }, 
{ IDT, NOQTEV }, 
{ QAYTAR, CRG1 }, 
{ CRG1, NOQTEV }, 
{ QAYTAR, CRG2 }, 
{ CRG2, NOQTEV }, 
{ QAYTAR, NUMB }, 
{ NUMB, NOQTEV }, 
{ QAYTAR, CHR }, 
{ CHR, NOQTEV }, 
{ QAYTAR, FLOAT }, 
{ FLOAT, NOQTEV }, 
{ QAYTAR, EXPR }, 
{ EXPR, NOQTEV }, 
{ QAYTAR, BRK_VAL }, 
{ BRK_VAL, NOQTEV }, 
{ QAYTAR, NOQTEV }, 
{ IDT, BRK_EMP }, 
{ IDT, BRK_VAL }, 
{ IDT, BRK_SEQ }, 
{ IDT, POSSIG }, 
{ POSSIG, IDT }, 
{ IDT, POSSIG }, 
{ POSSIG, CRG1 }, 
{ IDT, POSSIG }, 
{ POSSIG, CRG2 }, 
{ IDT, POSSIG }, 
{ POSSIG, NUMB }, 
{ IDT, POSSIG }, 
{ POSSIG, CHR }, 
{ IDT, POSSIG }, 
{ POSSIG, FLOAT }, 
{ IDT, POSSIG }, 
{ POSSIG, EXPR }, 
{ IDT, POSSIG }, 
{ POSSIG, BRK_VAL }, 
{ IDT, NEGSIG }, 
{ NEGSIG, IDT }, 
{ IDT, NEGSIG }, 
{ NEGSIG, CRG1 }, 
{ IDT, NEGSIG }, 
{ NEGSIG, CRG2 }, 
{ IDT, NEGSIG }, 
{ NEGSIG, NUMB }, 
{ IDT, NEGSIG }, 
{ NEGSIG, CHR }, 
{ IDT, NEGSIG }, 
{ NEGSIG, FLOAT }, 
{ IDT, NEGSIG }, 
{ NEGSIG, EXPR }, 
{ IDT, NEGSIG }, 
{ NEGSIG, BRK_VAL }, 
{ IDT, MULT }, 
{ MULT, IDT }, 
{ IDT, MULT }, 
{ MULT, CRG1 }, 
{ IDT, MULT }, 
{ MULT, CRG2 }, 
{ IDT, MULT }, 
{ MULT, NUMB }, 
{ IDT, MULT }, 
{ MULT, CHR }, 
{ IDT, MULT }, 
{ MULT, FLOAT }, 
{ IDT, MULT }, 
{ MULT, EXPR }, 
{ IDT, MULT }, 
{ MULT, BRK_VAL }, 
{ IDT, DEL }, 
{ DEL, IDT }, 
{ IDT, DEL }, 
{ DEL, CRG1 }, 
{ IDT, DEL }, 
{ DEL, CRG2 }, 
{ IDT, DEL }, 
{ DEL, NUMB }, 
{ IDT, DEL }, 
{ DEL, CHR }, 
{ IDT, DEL }, 
{ DEL, FLOAT }, 
{ IDT, DEL }, 
{ DEL, EXPR }, 
{ IDT, DEL }, 
{ DEL, BRK_VAL }, 
{ IDT, PRCT }, 
{ PRCT, IDT }, 
{ IDT, PRCT }, 
{ PRCT, CRG1 }, 
{ IDT, PRCT }, 
{ PRCT, CRG2 }, 
{ IDT, PRCT }, 
{ PRCT, NUMB }, 
{ IDT, PRCT }, 
{ PRCT, CHR }, 
{ IDT, PRCT }, 
{ PRCT, FLOAT }, 
{ IDT, PRCT }, 
{ PRCT, EXPR }, 
{ IDT, PRCT }, 
{ PRCT, BRK_VAL }, 
{ CRG1, POSSIG }, 
{ POSSIG, IDT }, 
{ CRG1, POSSIG }, 
{ POSSIG, CRG1 }, 
{ CRG1, POSSIG }, 
{ POSSIG, CRG2 }, 
{ CRG1, POSSIG }, 
{ POSSIG, NUMB }, 
{ CRG1, POSSIG }, 
{ POSSIG, CHR }, 
{ CRG1, POSSIG }, 
{ POSSIG, FLOAT }, 
{ CRG1, POSSIG }, 
{ POSSIG, EXPR }, 
{ CRG1, POSSIG }, 
{ POSSIG, BRK_VAL }, 
{ CRG1, NEGSIG }, 
{ NEGSIG, IDT }, 
{ CRG1, NEGSIG }, 
{ NEGSIG, CRG1 }, 
{ CRG1, NEGSIG }, 
{ NEGSIG, CRG2 }, 
{ CRG1, NEGSIG }, 
{ NEGSIG, NUMB }, 
{ CRG1, NEGSIG }, 
{ NEGSIG, CHR }, 
{ CRG1, NEGSIG }, 
{ NEGSIG, FLOAT }, 
{ CRG1, NEGSIG }, 
{ NEGSIG, EXPR }, 
{ CRG1, NEGSIG }, 
{ NEGSIG, BRK_VAL }, 
{ CRG1, MULT }, 
{ MULT, IDT }, 
{ CRG1, MULT }, 
{ MULT, CRG1 }, 
{ CRG1, MULT }, 
{ MULT, CRG2 }, 
{ CRG1, MULT }, 
{ MULT, NUMB }, 
{ CRG1, MULT }, 
{ MULT, CHR }, 
{ CRG1, MULT }, 
{ MULT, FLOAT }, 
{ CRG1, MULT }, 
{ MULT, EXPR }, 
{ CRG1, MULT }, 
{ MULT, BRK_VAL }, 
{ CRG1, DEL }, 
{ DEL, IDT }, 
{ CRG1, DEL }, 
{ DEL, CRG1 }, 
{ CRG1, DEL }, 
{ DEL, CRG2 }, 
{ CRG1, DEL }, 
{ DEL, NUMB }, 
{ CRG1, DEL }, 
{ DEL, CHR }, 
{ CRG1, DEL }, 
{ DEL, FLOAT }, 
{ CRG1, DEL }, 
{ DEL, EXPR }, 
{ CRG1, DEL }, 
{ DEL, BRK_VAL }, 
{ CRG1, PRCT }, 
{ PRCT, IDT }, 
{ CRG1, PRCT }, 
{ PRCT, CRG1 }, 
{ CRG1, PRCT }, 
{ PRCT, CRG2 }, 
{ CRG1, PRCT }, 
{ PRCT, NUMB }, 
{ CRG1, PRCT }, 
{ PRCT, CHR }, 
{ CRG1, PRCT }, 
{ PRCT, FLOAT }, 
{ CRG1, PRCT }, 
{ PRCT, EXPR }, 
{ CRG1, PRCT }, 
{ PRCT, BRK_VAL }, 
{ CRG2, POSSIG }, 
{ POSSIG, IDT }, 
{ CRG2, POSSIG }, 
{ POSSIG, CRG1 }, 
{ CRG2, POSSIG }, 
{ POSSIG, CRG2 }, 
{ CRG2, POSSIG }, 
{ POSSIG, NUMB }, 
{ CRG2, POSSIG }, 
{ POSSIG, CHR }, 
{ CRG2, POSSIG }, 
{ POSSIG, FLOAT }, 
{ CRG2, POSSIG }, 
{ POSSIG, EXPR }, 
{ CRG2, POSSIG }, 
{ POSSIG, BRK_VAL }, 
{ CRG2, NEGSIG }, 
{ NEGSIG, IDT }, 
{ CRG2, NEGSIG }, 
{ NEGSIG, CRG1 }, 
{ CRG2, NEGSIG }, 
{ NEGSIG, CRG2 }, 
{ CRG2, NEGSIG }, 
{ NEGSIG, NUMB }, 
{ CRG2, NEGSIG }, 
{ NEGSIG, CHR }, 
{ CRG2, NEGSIG }, 
{ NEGSIG, FLOAT }, 
{ CRG2, NEGSIG }, 
{ NEGSIG, EXPR }, 
{ CRG2, NEGSIG }, 
{ NEGSIG, BRK_VAL }, 
{ CRG2, MULT }, 
{ MULT, IDT }, 
{ CRG2, MULT }, 
{ MULT, CRG1 }, 
{ CRG2, MULT }, 
{ MULT, CRG2 }, 
{ CRG2, MULT }, 
{ MULT, NUMB }, 
{ CRG2, MULT }, 
{ MULT, CHR }, 
{ CRG2, MULT }, 
{ MULT, FLOAT }, 
{ CRG2, MULT }, 
{ MULT, EXPR }, 
{ CRG2, MULT }, 
{ MULT, BRK_VAL }, 
{ CRG2, DEL }, 
{ DEL, IDT }, 
{ CRG2, DEL }, 
{ DEL, CRG1 }, 
{ CRG2, DEL }, 
{ DEL, CRG2 }, 
{ CRG2, DEL }, 
{ DEL, NUMB }, 
{ CRG2, DEL }, 
{ DEL, CHR }, 
{ CRG2, DEL }, 
{ DEL, FLOAT }, 
{ CRG2, DEL }, 
{ DEL, EXPR }, 
{ CRG2, DEL }, 
{ DEL, BRK_VAL }, 
{ CRG2, PRCT }, 
{ PRCT, IDT }, 
{ CRG2, PRCT }, 
{ PRCT, CRG1 }, 
{ CRG2, PRCT }, 
{ PRCT, CRG2 }, 
{ CRG2, PRCT }, 
{ PRCT, NUMB }, 
{ CRG2, PRCT }, 
{ PRCT, CHR }, 
{ CRG2, PRCT }, 
{ PRCT, FLOAT }, 
{ CRG2, PRCT }, 
{ PRCT, EXPR }, 
{ CRG2, PRCT }, 
{ PRCT, BRK_VAL }, 
{ NUMB, POSSIG }, 
{ POSSIG, IDT }, 
{ NUMB, POSSIG }, 
{ POSSIG, CRG1 }, 
{ NUMB, POSSIG }, 
{ POSSIG, CRG2 }, 
{ NUMB, POSSIG }, 
{ POSSIG, NUMB }, 
{ NUMB, POSSIG }, 
{ POSSIG, CHR }, 
{ NUMB, POSSIG }, 
{ POSSIG, FLOAT }, 
{ NUMB, POSSIG }, 
{ POSSIG, EXPR }, 
{ NUMB, POSSIG }, 
{ POSSIG, BRK_VAL }, 
{ NUMB, NEGSIG }, 
{ NEGSIG, IDT }, 
{ NUMB, NEGSIG }, 
{ NEGSIG, CRG1 }, 
{ NUMB, NEGSIG }, 
{ NEGSIG, CRG2 }, 
{ NUMB, NEGSIG }, 
{ NEGSIG, NUMB }, 
{ NUMB, NEGSIG }, 
{ NEGSIG, CHR }, 
{ NUMB, NEGSIG }, 
{ NEGSIG, FLOAT }, 
{ NUMB, NEGSIG }, 
{ NEGSIG, EXPR }, 
{ NUMB, NEGSIG }, 
{ NEGSIG, BRK_VAL }, 
{ NUMB, MULT }, 
{ MULT, IDT }, 
{ NUMB, MULT }, 
{ MULT, CRG1 }, 
{ NUMB, MULT }, 
{ MULT, CRG2 }, 
{ NUMB, MULT }, 
{ MULT, NUMB }, 
{ NUMB, MULT }, 
{ MULT, CHR }, 
{ NUMB, MULT }, 
{ MULT, FLOAT }, 
{ NUMB, MULT }, 
{ MULT, EXPR }, 
{ NUMB, MULT }, 
{ MULT, BRK_VAL }, 
{ NUMB, DEL }, 
{ DEL, IDT }, 
{ NUMB, DEL }, 
{ DEL, CRG1 }, 
{ NUMB, DEL }, 
{ DEL, CRG2 }, 
{ NUMB, DEL }, 
{ DEL, NUMB }, 
{ NUMB, DEL }, 
{ DEL, CHR }, 
{ NUMB, DEL }, 
{ DEL, FLOAT }, 
{ NUMB, DEL }, 
{ DEL, EXPR }, 
{ NUMB, DEL }, 
{ DEL, BRK_VAL }, 
{ NUMB, PRCT }, 
{ PRCT, IDT }, 
{ NUMB, PRCT }, 
{ PRCT, CRG1 }, 
{ NUMB, PRCT }, 
{ PRCT, CRG2 }, 
{ NUMB, PRCT }, 
{ PRCT, NUMB }, 
{ NUMB, PRCT }, 
{ PRCT, CHR }, 
{ NUMB, PRCT }, 
{ PRCT, FLOAT }, 
{ NUMB, PRCT }, 
{ PRCT, EXPR }, 
{ NUMB, PRCT }, 
{ PRCT, BRK_VAL }, 
{ CHR, POSSIG }, 
{ POSSIG, IDT }, 
{ CHR, POSSIG }, 
{ POSSIG, CRG1 }, 
{ CHR, POSSIG }, 
{ POSSIG, CRG2 }, 
{ CHR, POSSIG }, 
{ POSSIG, NUMB }, 
{ CHR, POSSIG }, 
{ POSSIG, CHR }, 
{ CHR, POSSIG }, 
{ POSSIG, FLOAT }, 
{ CHR, POSSIG }, 
{ POSSIG, EXPR }, 
{ CHR, POSSIG }, 
{ POSSIG, BRK_VAL }, 
{ CHR, NEGSIG }, 
{ NEGSIG, IDT }, 
{ CHR, NEGSIG }, 
{ NEGSIG, CRG1 }, 
{ CHR, NEGSIG }, 
{ NEGSIG, CRG2 }, 
{ CHR, NEGSIG }, 
{ NEGSIG, NUMB }, 
{ CHR, NEGSIG }, 
{ NEGSIG, CHR }, 
{ CHR, NEGSIG }, 
{ NEGSIG, FLOAT }, 
{ CHR, NEGSIG }, 
{ NEGSIG, EXPR }, 
{ CHR, NEGSIG }, 
{ NEGSIG, BRK_VAL }, 
{ CHR, MULT }, 
{ MULT, IDT }, 
{ CHR, MULT }, 
{ MULT, CRG1 }, 
{ CHR, MULT }, 
{ MULT, CRG2 }, 
{ CHR, MULT }, 
{ MULT, NUMB }, 
{ CHR, MULT }, 
{ MULT, CHR }, 
{ CHR, MULT }, 
{ MULT, FLOAT }, 
{ CHR, MULT }, 
{ MULT, EXPR }, 
{ CHR, MULT }, 
{ MULT, BRK_VAL }, 
{ CHR, DEL }, 
{ DEL, IDT }, 
{ CHR, DEL }, 
{ DEL, CRG1 }, 
{ CHR, DEL }, 
{ DEL, CRG2 }, 
{ CHR, DEL }, 
{ DEL, NUMB }, 
{ CHR, DEL }, 
{ DEL, CHR }, 
{ CHR, DEL }, 
{ DEL, FLOAT }, 
{ CHR, DEL }, 
{ DEL, EXPR }, 
{ CHR, DEL }, 
{ DEL, BRK_VAL }, 
{ CHR, PRCT }, 
{ PRCT, IDT }, 
{ CHR, PRCT }, 
{ PRCT, CRG1 }, 
{ CHR, PRCT }, 
{ PRCT, CRG2 }, 
{ CHR, PRCT }, 
{ PRCT, NUMB }, 
{ CHR, PRCT }, 
{ PRCT, CHR }, 
{ CHR, PRCT }, 
{ PRCT, FLOAT }, 
{ CHR, PRCT }, 
{ PRCT, EXPR }, 
{ CHR, PRCT }, 
{ PRCT, BRK_VAL }, 
{ FLOAT, POSSIG }, 
{ POSSIG, IDT }, 
{ FLOAT, POSSIG }, 
{ POSSIG, CRG1 }, 
{ FLOAT, POSSIG }, 
{ POSSIG, CRG2 }, 
{ FLOAT, POSSIG }, 
{ POSSIG, NUMB }, 
{ FLOAT, POSSIG }, 
{ POSSIG, CHR }, 
{ FLOAT, POSSIG }, 
{ POSSIG, FLOAT }, 
{ FLOAT, POSSIG }, 
{ POSSIG, EXPR }, 
{ FLOAT, POSSIG }, 
{ POSSIG, BRK_VAL }, 
{ FLOAT, NEGSIG }, 
{ NEGSIG, IDT }, 
{ FLOAT, NEGSIG }, 
{ NEGSIG, CRG1 }, 
{ FLOAT, NEGSIG }, 
{ NEGSIG, CRG2 }, 
{ FLOAT, NEGSIG }, 
{ NEGSIG, NUMB }, 
{ FLOAT, NEGSIG }, 
{ NEGSIG, CHR }, 
{ FLOAT, NEGSIG }, 
{ NEGSIG, FLOAT }, 
{ FLOAT, NEGSIG }, 
{ NEGSIG, EXPR }, 
{ FLOAT, NEGSIG }, 
{ NEGSIG, BRK_VAL }, 
{ FLOAT, MULT }, 
{ MULT, IDT }, 
{ FLOAT, MULT }, 
{ MULT, CRG1 }, 
{ FLOAT, MULT }, 
{ MULT, CRG2 }, 
{ FLOAT, MULT }, 
{ MULT, NUMB }, 
{ FLOAT, MULT }, 
{ MULT, CHR }, 
{ FLOAT, MULT }, 
{ MULT, FLOAT }, 
{ FLOAT, MULT }, 
{ MULT, EXPR }, 
{ FLOAT, MULT }, 
{ MULT, BRK_VAL }, 
{ FLOAT, DEL }, 
{ DEL, IDT }, 
{ FLOAT, DEL }, 
{ DEL, CRG1 }, 
{ FLOAT, DEL }, 
{ DEL, CRG2 }, 
{ FLOAT, DEL }, 
{ DEL, NUMB }, 
{ FLOAT, DEL }, 
{ DEL, CHR }, 
{ FLOAT, DEL }, 
{ DEL, FLOAT }, 
{ FLOAT, DEL }, 
{ DEL, EXPR }, 
{ FLOAT, DEL }, 
{ DEL, BRK_VAL }, 
{ FLOAT, PRCT }, 
{ PRCT, IDT }, 
{ FLOAT, PRCT }, 
{ PRCT, CRG1 }, 
{ FLOAT, PRCT }, 
{ PRCT, CRG2 }, 
{ FLOAT, PRCT }, 
{ PRCT, NUMB }, 
{ FLOAT, PRCT }, 
{ PRCT, CHR }, 
{ FLOAT, PRCT }, 
{ PRCT, FLOAT }, 
{ FLOAT, PRCT }, 
{ PRCT, EXPR }, 
{ FLOAT, PRCT }, 
{ PRCT, BRK_VAL }, 
{ EXPR, POSSIG }, 
{ POSSIG, IDT }, 
{ EXPR, POSSIG }, 
{ POSSIG, CRG1 }, 
{ EXPR, POSSIG }, 
{ POSSIG, CRG2 }, 
{ EXPR, POSSIG }, 
{ POSSIG, NUMB }, 
{ EXPR, POSSIG }, 
{ POSSIG, CHR }, 
{ EXPR, POSSIG }, 
{ POSSIG, FLOAT }, 
{ EXPR, POSSIG }, 
{ POSSIG, EXPR }, 
{ EXPR, POSSIG }, 
{ POSSIG, BRK_VAL }, 
{ EXPR, NEGSIG }, 
{ NEGSIG, IDT }, 
{ EXPR, NEGSIG }, 
{ NEGSIG, CRG1 }, 
{ EXPR, NEGSIG }, 
{ NEGSIG, CRG2 }, 
{ EXPR, NEGSIG }, 
{ NEGSIG, NUMB }, 
{ EXPR, NEGSIG }, 
{ NEGSIG, CHR }, 
{ EXPR, NEGSIG }, 
{ NEGSIG, FLOAT }, 
{ EXPR, NEGSIG }, 
{ NEGSIG, EXPR }, 
{ EXPR, NEGSIG }, 
{ NEGSIG, BRK_VAL }, 
{ EXPR, MULT }, 
{ MULT, IDT }, 
{ EXPR, MULT }, 
{ MULT, CRG1 }, 
{ EXPR, MULT }, 
{ MULT, CRG2 }, 
{ EXPR, MULT }, 
{ MULT, NUMB }, 
{ EXPR, MULT }, 
{ MULT, CHR }, 
{ EXPR, MULT }, 
{ MULT, FLOAT }, 
{ EXPR, MULT }, 
{ MULT, EXPR }, 
{ EXPR, MULT }, 
{ MULT, BRK_VAL }, 
{ EXPR, DEL }, 
{ DEL, IDT }, 
{ EXPR, DEL }, 
{ DEL, CRG1 }, 
{ EXPR, DEL }, 
{ DEL, CRG2 }, 
{ EXPR, DEL }, 
{ DEL, NUMB }, 
{ EXPR, DEL }, 
{ DEL, CHR }, 
{ EXPR, DEL }, 
{ DEL, FLOAT }, 
{ EXPR, DEL }, 
{ DEL, EXPR }, 
{ EXPR, DEL }, 
{ DEL, BRK_VAL }, 
{ EXPR, PRCT }, 
{ PRCT, IDT }, 
{ EXPR, PRCT }, 
{ PRCT, CRG1 }, 
{ EXPR, PRCT }, 
{ PRCT, CRG2 }, 
{ EXPR, PRCT }, 
{ PRCT, NUMB }, 
{ EXPR, PRCT }, 
{ PRCT, CHR }, 
{ EXPR, PRCT }, 
{ PRCT, FLOAT }, 
{ EXPR, PRCT }, 
{ PRCT, EXPR }, 
{ EXPR, PRCT }, 
{ PRCT, BRK_VAL }, 
{ BRK_VAL, POSSIG }, 
{ POSSIG, IDT }, 
{ BRK_VAL, POSSIG }, 
{ POSSIG, CRG1 }, 
{ BRK_VAL, POSSIG }, 
{ POSSIG, CRG2 }, 
{ BRK_VAL, POSSIG }, 
{ POSSIG, NUMB }, 
{ BRK_VAL, POSSIG }, 
{ POSSIG, CHR }, 
{ BRK_VAL, POSSIG }, 
{ POSSIG, FLOAT }, 
{ BRK_VAL, POSSIG }, 
{ POSSIG, EXPR }, 
{ BRK_VAL, POSSIG }, 
{ POSSIG, BRK_VAL }, 
{ BRK_VAL, NEGSIG }, 
{ NEGSIG, IDT }, 
{ BRK_VAL, NEGSIG }, 
{ NEGSIG, CRG1 }, 
{ BRK_VAL, NEGSIG }, 
{ NEGSIG, CRG2 }, 
{ BRK_VAL, NEGSIG }, 
{ NEGSIG, NUMB }, 
{ BRK_VAL, NEGSIG }, 
{ NEGSIG, CHR }, 
{ BRK_VAL, NEGSIG }, 
{ NEGSIG, FLOAT }, 
{ BRK_VAL, NEGSIG }, 
{ NEGSIG, EXPR }, 
{ BRK_VAL, NEGSIG }, 
{ NEGSIG, BRK_VAL }, 
{ BRK_VAL, MULT }, 
{ MULT, IDT }, 
{ BRK_VAL, MULT }, 
{ MULT, CRG1 }, 
{ BRK_VAL, MULT }, 
{ MULT, CRG2 }, 
{ BRK_VAL, MULT }, 
{ MULT, NUMB }, 
{ BRK_VAL, MULT }, 
{ MULT, CHR }, 
{ BRK_VAL, MULT }, 
{ MULT, FLOAT }, 
{ BRK_VAL, MULT }, 
{ MULT, EXPR }, 
{ BRK_VAL, MULT }, 
{ MULT, BRK_VAL }, 
{ BRK_VAL, DEL }, 
{ DEL, IDT }, 
{ BRK_VAL, DEL }, 
{ DEL, CRG1 }, 
{ BRK_VAL, DEL }, 
{ DEL, CRG2 }, 
{ BRK_VAL, DEL }, 
{ DEL, NUMB }, 
{ BRK_VAL, DEL }, 
{ DEL, CHR }, 
{ BRK_VAL, DEL }, 
{ DEL, FLOAT }, 
{ BRK_VAL, DEL }, 
{ DEL, EXPR }, 
{ BRK_VAL, DEL }, 
{ DEL, BRK_VAL }, 
{ BRK_VAL, PRCT }, 
{ PRCT, IDT }, 
{ BRK_VAL, PRCT }, 
{ PRCT, CRG1 }, 
{ BRK_VAL, PRCT }, 
{ PRCT, CRG2 }, 
{ BRK_VAL, PRCT }, 
{ PRCT, NUMB }, 
{ BRK_VAL, PRCT }, 
{ PRCT, CHR }, 
{ BRK_VAL, PRCT }, 
{ PRCT, FLOAT }, 
{ BRK_VAL, PRCT }, 
{ PRCT, EXPR }, 
{ BRK_VAL, PRCT }, 
{ PRCT, BRK_VAL }, 

};




#endif