

/* RULE SET  */

 
  PRG1 -> PRG KOD1 SON
  PRG1 -> PRG VAR1 KOD1  SON 
  FE2 -> OPNBRK FE1  CLSBRK
  FUNK_ELAN -> FDECL FE1 CLSBRK
  FUNK_ELAN -> FDECL CLSBRK
  KOD1 -> KOD COLON
  KOD1 -> KOD KOLON KODDATA
  FUNK_BODY -> OPNBLK  VAR1  KOD1  CLSBLK
  FUNK_BODY -> OPNBLK KOD1 CLSBLK
  FUNKS -> FUNK FUNK  
  FUNKS -> FUNK FUNKS
  FUNKS -> FUNKS FUNK
  FUNKS -> FUNKS FUNKS
  FUNK -> FUNK_ELAN FUNK_BODY
  PRG2 -> PRG1
  PRG2 -> PRG1 FUNK
  PRG2 -> PRG1 FUNKS
  KODDATA -> OPNBLK KODDATA CLSBLK
  KODDATA -> !YOXSA KODDATA  KODDATA
  KODDATA -> EGER_EXP2  KODDATA YOXSA KODDATA
  KODDATA -> NEQEDERKI2 KODDATA
  KODDATA -> EGER_EXP2 KODDATA !YOXSA
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL2 HAL1 CLSBLK
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL3 HAL1 CLSBLK
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL1 CLSBLK
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL2 CLSBLK
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL3 CLSBLK
  KODDATA -> DOVR_EXP KODDATA
  KODDATA -> FCALL1 NOQTEV
  KODDATA -> (DXILET3 CAPET3 ASGN_OP EMTYOP DAVAMET1 DAYAN1 QAYTAR1)
  NEQEDERKI2 -> NEQEDERKI1 SHERT CLSBRK TAKRARET
  EGER_EXP2 -> EXEG_EXP1 SHERT CLSBRK ONDA 
  FE1 ->  FE1  VERGUL  FE1
  FE1 -> (TAM1 SIMVOL1 KESR1)
  EMPBRK -> OPNBRK CLSBRK
  EMPTYOP -> OPNBLK CLSBLK
  DAVAMET1 -> DAVAMET NOQTEV
  DAYAN1 -> DAYAN NOQTEV
  NEQEDERKI1 -> NEQEDERKI OPNBRK
  EGER_EXP1 -> EGER OPNBRK
  DOVR_EXP -> DOVR OPNBRK (IDT CRG12) (ARTSIN AZALSIN) (IDT CRG12 NUMB) NEGSIG
    (DAN DEN)  (IDT CRG12 NUMB) NEGSIG (AA EE YA YE) KIMI CLSBRK TEKRARET
  ASHN_OP -> (IDT CRG12) ASGN (INACFE FCALL1) NOQTEV
  CAPET3 -> CAPET2 CLSBRK NOQTEV
  CAPET2 -> CAPET2 VDEC
  CAPET2 -> CAPET1 INACSFE
  CAPET1 -> CAPET OPNBRK
  DAXILET3 -> DAXILET2 CLSBRK NOQTEV
  DAXILET2 -> DAXILET2 VDEC
  DAXILET2 -> DAXILET1  IA
  DAXILET1 -> DAXIL OPNBRK
  HAL1 -> HAL (NUMB CHR) COLON
  HAL1 -> HAL1 HAL1
  HAL1 -> SUSMA COLON
  HAL2 -> HAL1 KODDATA (HAL1 HAL2 CLSBLK)
  HAL3 -> HAL2 HAL2
  HAL3 -> HAL2 HAL3
  HAL3 -> HAL3 HAL3
  HAL3 -> HAL3 HAL2
  SEC1 -> SEC OPNBRK
  VDEC -> *FCALL INACSFEF // FCALL NOT USED
  VDEC -> VERGUL INACSFE 
  VDEC -> VDEC VDEC
  FDECL -> FUNKSIYA IDT ONPBRK
  FCALL -> IDT OPNBRK
  VAR1 -> VAR1 (TAM2 KESR2 SIMVOL2)
  VAR1 -> VAR COLON
  SIMVOL2 -> SIMVOL1 NOQTEV
  KESR2 -> KESR1 NOQTEV
  TAM2 -> TAM1 NOQTEV
  SIMVOL1 -> SIMVOL1 VERGUL IA
  SIMVOL1 -> SIMVOL IA
  TAM1 -> TAM1 VERGUL IA
  TAM1 -> TAM IA
  KESR1 -> KESR1 VERGUL IA
  KESR1 -> KESR IA
  SHERT -> SHERT (VE VEYA) SHERT
  SHERT -> INACFEF COND INACFEF 
  OPNBRK INACFEF CLSBRK ->  INACFEF
  CRG2 -> IDT ARYOPN NUMB ARYCLS ARYOPN NUMB ARYCLS
  CRG2 -> IDT ARYOPN (INACE) ARYCLS  ARYOPN (INACE) ARYCLS
  CRG1 -> IDT ARYOPN NUMB ARYCLS
  CRG1 -> ARYOPN (INACE) ARYCLS
  FCALL1 -> FCALL CLSBRK
  FCALL1 -> FCALL VDEC CLSBRK
  QAYTAR1 -> QAYTAR NOQTEV
  QAYTAR1 -> QAYTAR INACSFE NOQTEV
  EXPR -> INAFEF (LP HP) INAFEF 



			/* VOCABULARY  */




 
  PRG1 -> PRG KOD1 SON
  PRG1 -> PRG VAR1 KOD1  SON 
      
  FE2  -> OPNBRK FE1  CLSBRK
 
  FUNK_ELAN ->  FDECL FE1 CLSBRK
  FUNK_ELAN -> FDECL CLSBRK

  KOD1 -> KOD COLON
  KOD1 -> KOD KOLON KODDATA

  FUNK_BODY ->  OPNBLK  VAR1  KOD1  CLSBLK
  FUNK_BODY -> OPNBLK KOD1 CLSBLK

  FUNKS ->  FUNK FUNK  
  FUNKS ->  FUNK FUNKS
  FUNKS ->  FUNKS FUNK
  FUNKS ->  FUNKS FUNKS

  FUNK -> FUNK_ELAN FUNK_BODY

  PRG2 -> PRG1
  PRG2 -> PRG1 FUNK
  PRG2 -> PRG1 FUNKS

  KODDATA -> OPNBLK KODDATA CLSBLK
  KODDATA -> !YOXSA KODDATA  KODDATA
  KODDATA -> EGER_EXP2  KODDATA YOXSA KODDATA
  KODDATA -> NEQEDERKI2 KODDATA
  KODDATA -> EGER_EXP2 KODDATA !YOXSA
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL2 HAL1 CLSBLK
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL3 HAL1 CLSBLK
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL1 CLSBLK
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL2 CLSBLK
  KODDATA -> SEC1  IDT CLSBRK OPNBLK HAL3 CLSBLK
  KODDATA -> DOVR_EXP KODDATA
  KODDATA -> FCALL1 NOQTEV
  KODDATA -> (DXILET3 CAPET3 ASGN_OP EMTYOP DAVAMET1 DAYAN1 QAYTAR1)

  NEQEDERKI2 -> NEQEDERKI1 SHERT CLSBRK TAKRARET

  EGER_EXP2 -> EXEG_EXP1 SHERT CLSBRK ONDA 

  FE1 ->  FE1  VERGUL  FE1
  FE1 -> (TAM1 SIMVOL1 KESR1)

  EMPBRK -> OPNBRK CLSBRK

  EMPTYOP -> OPNBLK CLSBLK

  DAVAMET1 -> DAVAMET NOQTEV

  DAYAN1 -> DAYAN NOQTEV

  NEQEDERKI1 -> NEQEDERKI OPNBRK

  EGER_EXP1 -> EGER OPNBRK

  DOVR_EXP -> DOVR OPNBRK (IDT CRG12) (ARTSIN AZALSIN) (IDT CRG12 NUMB) NEGSIG
    (DAN DEN)  (IDT CRG12 NUMB) NEGSIG (AA EE YA YE) KIMI CLSBRK TEKRARET

  ASHN_OP -> (IDT CRG12) ASGN (INACFE FCALL1) NOQTEV

  CAPET3 -> CAPET2 CLSBRK NOQTEV
  
  CAPET2 -> CAPET2 VDEC
  
  CAPET2 -> CAPET1 INACSFE
  
  CAPET1 -> CAPET OPNBRK

  DAXILET3 -> DAXILET2 CLSBRK NOQTEV
  
  DAXILET2 -> DAXILET2 VDEC
  
  DAXILET2 -> DAXILET1  IA
  
  DAXILET1 -> DAXIL OPNBRK

  HAL1 -> HAL (NUMB CHR) COLON
  HAL1 -> HAL1 HAL1
  HAL1 -> SUSMA COLON

  HAL2 -> HAL1 KODDATA (HAL1 HAL2 CLSBLK)

  HAL3 -> HAL2 HAL2
  HAL3 -> HAL2 HAL3
  HAL3 -> HAL3 HAL3
  HAL3 -> HAL3 HAL2

  SEC1 -> SEC OPNBRK

  VDEC -> *FCALL INACSFEF // FCALL NOT USED
  VDEC -> VERGUL INACSFE 
  VDEC -> VDEC VDEC

  FDECL -> FUNKSIYA IDT ONPBRK

  FCALL -> IDT OPNBRK

  VAR1 -> VAR1 (TAM2 KESR2 SIMVOL2)
  VAR1-> VAR COLON

  SIMVOL2 -> SIMVOL1 NOQTEV

  KESR2 -> KESR1 NOQTEV

  TAM2 -> TAM1 NOQTEV

  SIMVOL1 -> SIMVOL1 VERGUL IA
  SIMVOL1-> SIMVOL IA

  TAM1 -> TAM1 VERGUL IA
  TAM1-> TAM IA
 
  KESR1-> KESR1 VERGUL IA
  KESR1-> KESR IA

  SHERT -> SHERT (VE VEYA) SHERT
  SHERT -> INACFEF COND INACFEF 

  OPNBRK INACFEF CLSBRK ->  INACFEF

  CRG2-> IDT ARYOPN NUMB ARYCLS ARYOPN NUMB ARYCLS
  CRG2 -> IDT ARYOPN (INACE) ARYCLS  ARYOPN (INACE) ARYCLS

  CRG1-> IDT ARYOPN NUMB ARYCLS
  CRG1->  ARYOPN (INACE) ARYCLS

  FCALL1->  FCALL CLSBRK
  FCALL1 -> FCALL VDEC CLSBRK

  QAYTAR1-> QAYTAR NOQTEV
  QAYTAR1-> QAYTAR INACSFE NOQTEV

  EXPR->  INAFEF (LP HP) INAFEF 









