A theme common to nearly all versions is that of the hero—Köroğlu, literally "son of the blind man", or more directly translated as 'Blindson' (analogous with the English surname Richardson, sons of Richard), defending his clan or tribe against threats from outside. In many of the versions, Köroğlu earns his name from the wrongful blinding of his father, an act for which the son takes his revenge and which initiates his series of adventures. He is portrayed as a bandit and an ozan.

A number of songs and melodies attributed to Köroğlu survives in the folk tradition. These songs and melodies differ from most other Turkic folk music in two aspects: they follow a rhythm of 5/8 (ONE-two ONE-two-three) and they depict heroic acts and persons.

The most common version of the tale describes Köroğlu as Rusen Ali, the son of the stableman Koca Yusuf lives in Dörtdivan under the service of the Bey of Bolu. One day, Yusuf comes across a filly which, to his trained eye, is an animal that will turn into a fine beast if well-fed. Bey wants to give good fillies to the Sultan as a present to repair their worsening relationship. However the Bey does not know enough about horses to appreciate the thin, famished animal that is presented to him. Being a man of foul and easily provoked temper, he suspects that he is being mocked and orders the poor worker to be blinded. His son, therefore, gains his nickname and harbors an ever-increasing hatred towards the Bey of Bolu in his heart as he grows up. The mare, which he names Kırat (kır at means literally "gray horse"; the word kırat can also mean "carat", "quality"), grows up with him and indeed turns into an animal of legendary stature and strength.

One day, Hızır shows himself to Yusuf in a dream and tells him that soon, the waters of the river Aras will flow briefly as a kind of thick foam and whoever drinks that foam will be cured of whatever physical problems that may be ailing him, including blindness and aging. Yusuf goes to the shore of the river with his son, but his son drinks the foam before he does. As this miracle can give everlasting health and youth to only one man, Yusuf loses his chance to see again; and dies a few days later, ordering his son to avenge him.

In some versions of the story, neither Yusuf nor his son can drink from the foam. Yusuf is warned by Hızır just before the phenomenon occurs, but being an old and blind man, he cannot reach the river in time. Köroğlu is by the river when the foam starts flowing, but, as he is ignorant of the significance of the event, he does not drink from the river. Instead, his horse Kırat does and becomes immortal.

After his fathers death, Köroğlu takes up arms against the Bey. As he has only a few followers, he does not engage the army of Bolu directly and uses guerrilla tactics instead. He raids and plunders his former master's property, and eludes his would-be captors by staying on the move and fleeing to distant lands whenever his enemy organises a large-scale campaign to capture him.

Before he succeeds, however, the knowledge of firearms are carried by merchants to Anatolia. Even the simple guns of the time are sufficient to change the ways of the warriors forever: The balance of power is upset by the "holed iron", as Köroğlu calls the tool when he first sees one, and the Beys of Northern Anatolia engage in brutal warfare with each other. The fighting goes on and on, with no end in sight. Köroğlu realizes that even if he succeeds in bringing down the Bey of Bolu, he wont be able to bring back the old, chivalric world that he was born into. The warrior-poet disbands his followers and fades into obscurity, leaving only these lines behind:[1]
