#ifndef SEHVLER_3
#define SEHVLER_3

int terminal_set_len = 47;

int terminal_set[]={ 
   TAM     
,  KESR    
,  SIMVOL  
,  IDT     
,  VERGUL   
,  NOQTEV  
,  OPNBRK  
,  STR     
,  CHR     
,  CLSBRK  
,  NUMB    
,  POSSIG  
,  NEGSIG  
,  COLON   
,  ARYOPN  
,  ARYCLS  
,  ASGN     
,  MULT     
,  DEL      
,  PRCT     
,  EGER     
,  NIDA     
,  GRT      
,  LES      
,  VE       
,  VEYA     
,  FILESON  
,  OPNBLK   
,  CLSBLK   
,  YOXSA    
,  BERABER  
,  FERQLI 
,  LESEQU 
,  GRTEQU 
,  EMPTOK 
,  SHERT   
, FLOAT 
, FUNKSIYA 
, QAYTAR 
, NEQEDERKI 
, DAVAMET 
, DAYAN 
, SEC
, HAL 
, SAY 
, INCREMENT  
, DECREMENT 
};

struct follow{
	int id;
	int fol[277];
	int len;

};


int follow_set_new_len = 277;

struct follow follow_set_new[] = {

{ PRG , { }, 0 }, 
{ VAR , { }, 0 }, 
{ TAM , { IDT, CRG1, CRG2, SEQ, }, 4 }, 
{ KESR , { }, 0 }, 
{ SIMVOL , { }, 0 }, 
{ IDT , { ASGN, NOQTEV, VERGUL, GRT, LES, BERABER, FERQLI, GRTEQU, LESEQU, CLSBRK, ARYCLS, ARYBRK_VAL, DECREMENT,   INCREMENT,  BRK_EMP, BRK_VAL, BRK_SEQ, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, MULT, MULT, MULT, MULT, MULT, MULT, MULT, MULT, DEL, DEL, DEL, DEL, DEL, DEL, DEL, DEL, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, }, 122 }, 
{ VERGUL , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, STR, EXPR, BRK_VAL, SEQ, }, 100 }, 
{ NOQTEV , { }, 0 }, 
{ KOD , { }, 0 }, 
{ CAPET , { }, 0 }, 
{ OPNBRK , { CLSBRK, IDT, CRG1, CRG2, NUMB, FLOAT, CHR, EXPR, STR, BRK_VAL, SHERT, BRK_SHERT, SEQ, BRK_SEQ, BRK_EMP, }, 15 }, 
{ STR , { NOQTEV, NOQTEV, NOQTEV, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, CLSBRK, }, 14 }, 
{ CHR , { NOQTEV, NOQTEV, NOQTEV, COLON, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, GRT, GRT, GRT, GRT, GRT, GRT, GRT, GRT, LES, LES, LES, LES, LES, LES, LES, LES, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, CLSBRK, ARYCLS, NOQTEV, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, MULT, MULT, MULT, MULT, MULT, MULT, MULT, MULT, DEL, DEL, DEL, DEL, DEL, DEL, DEL, DEL, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, }, 105 }, 
{ CLSBRK , { }, 0 }, 
{ SON , { }, 0 }, 
{ DOT , { }, 0 }, 
{ LEXEM , { }, 0 }, 
{ NUMB , { NOQTEV, NOQTEV, NOQTEV, COLON, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, GRT, GRT, GRT, GRT, GRT, GRT, GRT, GRT, LES, LES, LES, LES, LES, LES, LES, LES, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, CLSBRK, ARYCLS, NOQTEV, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, MULT, MULT, MULT, MULT, MULT, MULT, MULT, MULT, DEL, DEL, DEL, DEL, DEL, DEL, DEL, DEL, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, }, 105 }, 
{ SIGN , { }, 0 }, 
{ DIG , { }, 0 }, 
{ POSDIG , { }, 0 }, 
{ POSNUMB , { }, 0 }, 
{ SNUMB , { }, 0 }, 
{ POSSIG , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ NEGSIG , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ SLC , { }, 0 }, 
{ MLC , { }, 0 }, 
{ SPS , { }, 0 }, 
{ COLON , { }, 0 }, 
{ ARYOPN , { IDT, CRG1, CRG2, NUMB, FLOAT, CHR, EXPR, }, 7 }, 
{ ARYCLS , { }, 0 }, 
{ ASGN , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, STR, FCALL1, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, STR, FCALL1, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, STR, FCALL1, BRK_VAL, }, 30 }, 
{ MULT , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ DEL , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ PRCT , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ XAR , { }, 0 }, 
{ DAXIL , { }, 0 }, 
{ EGER , { BRK_SHERT, }, 1 }, 
{ NIDA , { }, 0 }, 
{ GRT , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ LES , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ VE , { SHERT, SHERT, BRK_SHERT, BRK_SHERT, }, 4 }, 
{ VEYA , { SHERT, SHERT, BRK_SHERT, BRK_SHERT, }, 4 }, 
{ FILESON , { }, 0 }, 
{ OPNBLK , { KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, CLSBLK, HAL2, }, 6 }, 
{ CLSBLK , { }, 0 }, 
{ ONDA , { }, 0 }, 
{ YOXSA , { SIMPLE_OPER, COMP_OPER, BLOCK, SIMPLE_OPER, COMP_OPER, BLOCK, SIMPLE_OPER, COMP_OPER, BLOCK, SIMPLE_OPER, COMP_OPER, BLOCK, }, 12 }, 
{ BERABER , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ FERQLI , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ LESEQU , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ GRTEQU , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, }, 64 }, 
{ EMPTOK , { }, 0 }, 
{ SHERT , { VE, VEYA, VE, VEYA, CLSBRK, }, 5 }, 
{ IFAD , { }, 0 }, 
{ DOVR , { }, 0 }, 
{ ARTSIN , { }, 0 }, 
{ AZALSIN , { }, 0 }, 
{ ADDIM , { }, 0 }, 
{ KIMI , { }, 0 }, 
{ CRG1 , { NOQTEV, ASGN, ASGN, NOQTEV, ASGN, ASGN, ASGN, ASGN, ASGN, ASGN, ASGN, ASGN, NOQTEV, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, GRT, GRT, GRT, GRT, GRT, GRT, GRT, GRT, LES, LES, LES, LES, LES, LES, LES, LES, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, CLSBRK, ARYCLS, ARYBRK_VAL, DECREMENT, NOQTEV, INCREMENT, NOQTEV, NOQTEV, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, MULT, MULT, MULT, MULT, MULT, MULT, MULT, MULT, DEL, DEL, DEL, DEL, DEL, DEL, DEL, DEL, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, }, 119 }, 
{ CRG2 , { NOQTEV, NOQTEV, ASGN, ASGN, ASGN, NOQTEV, ASGN, ASGN, ASGN, ASGN, ASGN, ASGN, ASGN, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, GRT, GRT, GRT, GRT, GRT, GRT, GRT, GRT, LES, LES, LES, LES, LES, LES, LES, LES, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, CLSBRK, ARYCLS, DECREMENT, NOQTEV, INCREMENT, NOQTEV, NOQTEV, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, MULT, MULT, MULT, MULT, MULT, MULT, MULT, MULT, DEL, DEL, DEL, DEL, DEL, DEL, DEL, DEL, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, }, 118 }, 
{ TEKRARET , { }, 0 }, 
{ DAN , { }, 0 }, 
{ DEN , { }, 0 }, 
{ CAPET_OP , { }, 0 }, 
{ DOVR_OP , { }, 0 }, 
{ BLOCK , { FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_FUNK, CLSBLK, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_PART, YOXSA, YOXSA, YOXSA, YOXSA, YOXSA_OPER, TEXT, KOD_FUNK, FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 23 }, 
{ BIRTIP , { }, 0 }, 
{ TIPLER , { }, 0 }, 
{ EGER_OP , { }, 0 }, 
{ ASGN_OP , { }, 0 }, 
{ DAXIL_OP , { }, 0 }, 
{ BLOKSUZ , { }, 0 }, 
{ BLOKLU , { }, 0 }, 
{ KODDATALAR , { }, 0 }, 
{ BLOKLUDATA , { }, 0 }, 
{ YE , { }, 0 }, 
{ YA , { }, 0 }, 
{ EE , { }, 0 }, 
{ AA , { }, 0 }, 
{ DOVR_EXP , { }, 0 }, 
{ EGER_EXP , { }, 0 }, 
{ DOVR_BLOKSUZ , { }, 0 }, 
{ EGER_BLOKSUZ , { }, 0 }, 
{ YOXSA_BLOKSUZ , { }, 0 }, 
{ KODDATA , { }, 0 }, 
{ DOVR_BLOKLU , { }, 0 }, 
{ EGER_BLOKLU , { }, 0 }, 
{ YOXSA_BLOKLU , { }, 0 }, 
{ EGER_TEK_BLOKSUZ , { }, 0 }, 
{ EGER_TAM_BLOKSUZ , { }, 0 }, 
{ TAM1 , { }, 0 }, 
{ TAM2 , { }, 0 }, 
{ KESR1 , { }, 0 }, 
{ KESR2 , { }, 0 }, 
{ SIMVOL1 , { }, 0 }, 
{ SIMVOL2 , { }, 0 }, 
{ SIMVOL3 , { }, 0 }, 
{ VAR1 , { }, 0 }, 
{ VAR2 , { }, 0 }, 
{ DAXILET1 , { }, 0 }, 
{ DAXILET2 , { }, 0 }, 
{ CAPET1 , { }, 0 }, 
{ CAPET2 , { }, 0 }, 
{ EGER_EXP1 , { }, 0 }, 
{ EGER_EXP2 , { SIMPLE_OPER, SIMPLE_OPER, SIMPLE_OPER, COMP_OPER, COMP_OPER, COMP_OPER, BLOCK, BLOCK, BLOCK, SIMPLE_OPER, COMP_OPER, BLOCK, SIMPLE_OPER, COMP_OPER, BLOCK, SIMPLE_OPER, COMP_OPER, BLOCK, }, 18 }, 
{ KOD1 , { }, 0 }, 
{ PRG1 , { }, 0 }, 
{ BADSTR , { }, 0 }, 
{ BADIDT , { }, 0 }, 
{ BADCHR , { }, 0 }, 
{ DAXILET3 , { }, 0 }, 
{ EMPTYOP , { }, 0 }, 
{ CAPET3 , { }, 0 }, 
{ EXPR , { NOQTEV, NOQTEV, NOQTEV, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, GRT, GRT, GRT, GRT, GRT, GRT, GRT, GRT, LES, LES, LES, LES, LES, LES, LES, LES, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, CLSBRK, ARYCLS, NOQTEV, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, MULT, MULT, MULT, MULT, MULT, MULT, MULT, MULT, DEL, DEL, DEL, DEL, DEL, DEL, DEL, DEL, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, }, 104 }, 
{ OPR , { }, 0 }, 
{ BRK , { }, 0 }, 
{ FILEBEG , { }, 0 }, 
{ FLOAT_HALF , { }, 0 }, 
{ FLOAT , { NOQTEV, NOQTEV, NOQTEV, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, GRT, GRT, GRT, GRT, GRT, GRT, GRT, GRT, LES, LES, LES, LES, LES, LES, LES, LES, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, CLSBRK, ARYCLS, NOQTEV, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, MULT, MULT, MULT, MULT, MULT, MULT, MULT, MULT, DEL, DEL, DEL, DEL, DEL, DEL, DEL, DEL, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, }, 104 }, 
{ FUNKSIYA , { FCALL1, }, 1 }, 
{ FUNK_ELAN , { }, 0 }, 
{ FUNK_BODY , { }, 0 }, 
{ EMPBRK , { }, 0 }, 
{ FE1 , { }, 0 }, 
{ FE2 , { }, 0 }, 
{ FUNK , { FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_FUNK, TEXT, KOD_FUNK, FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 13 }, 
{ FUNKS , { }, 0 }, 
{ FCALL , { }, 0 }, 
{ FCALL1 , { BLOCK, NOQTEV, NOQTEV, NOQTEV, NOQTEV, }, 5 }, 
{ VDEC , { NOQTEV, }, 1 }, 
{ DUMMY , { }, 0 }, 
{ FDECL , { }, 0 }, 
{ PRG2 , { }, 0 }, 
{ QAYTAR , { IDT, CRG1, CRG2, NUMB, CHR, FLOAT, EXPR, BRK_VAL, NOQTEV, }, 9 }, 
{ QAYTAR1 , { }, 0 }, 
{ NEQEDERKI , { BRK_SHERT, }, 1 }, 
{ NEQEDERKI1 , { }, 0 }, 
{ NEQEDERKI2 , { SIMPLE_OPER, COMP_OPER, BLOCK, }, 3 }, 
{ DAVAMET , { NOQTEV, }, 1 }, 
{ DAYAN , { NOQTEV, }, 1 }, 
{ DAVAMET1 , { }, 0 }, 
{ DAYAN1 , { }, 0 }, 
{ SEC , { BRK_VAL, }, 1 }, 
{ SEC_OP , { }, 0 }, 
{ HAL , { NUMB, CHR, }, 2 }, 
{ HAL1 , { HAL1, HAL1S, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 6 }, 
{ HAL2 , { CLSBLK, HAL2, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 6 }, 
{ HAL3 , { }, 0 }, 
{ SEC1 , { OPNBLK, }, 1 }, 
{ SUSMA , { COLON, }, 1 }, 
{ START , { }, 0 }, 
{ STRUKT , { }, 0 }, 
{ STRUKT1 , { }, 0 }, 
{ STRUKT2 , { }, 0 }, 
{ STRUKT3 , { }, 0 }, 
{ YNT1 , { }, 0 }, 
{ YNT2 , { }, 0 }, 
{ STRMEM , { }, 0 }, 
{ YNTS , { }, 0 }, 
{ SINIF , { }, 0 }, 
{ MEXSUSI , { }, 0 }, 
{ UMUMI , { }, 0 }, 
{ QORUNAN , { }, 0 }, 
{ SINIF_HEAD , { }, 0 }, 
{ SINIF_HEAD_START , { }, 0 }, 
{ SINIF_BODY , { }, 0 }, 
{ SINIF_DECL , { }, 0 }, 
{ SINIF_TYPE , { }, 0 }, 
{ YENI_TIP , { }, 0 }, 
{ SNMEM , { }, 0 }, 
{ INIT_DOVR , { }, 0 }, 
{ CHECK_DOVR , { }, 0 }, 
{ STEP_DOVR , { }, 0 }, 
{ NEQ_TOP , { }, 0 }, 
{ SUS1 , { KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 4 }, 
{ HAL1S , { HAL1, HAL1S, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 6 }, 
{ FARGS , { }, 0 }, 
{ FPARM , { }, 0 }, 
{ FCALL_BEG , { }, 0 }, 
{ PUT_RET_ADDR , { }, 0 }, 
{ IDT_ADRS , { }, 0 }, 
{ CRG1_ADRS , { }, 0 }, 
{ CRG2_ADRS , { }, 0 }, 
{ CRG1_VAL , { }, 0 }, 
{ CRG2_VAL , { }, 0 }, 
{ IDT_VAL , { }, 0 }, 
{ IDT_OFST , { }, 0 }, 
{ CRG1_OFST , { }, 0 }, 
{ CRG2_OFST , { }, 0 }, 
{ STRMEM_VAL , { }, 0 }, 
{ CAPET_NUMB , { }, 0 }, 
{ CAPET_FLOAT , { }, 0 }, 
{ CAPET_CHR , { }, 0 }, 
{ CAPET_STR , { }, 0 }, 
{ CAPET_IDT , { }, 0 }, 
{ CAPET_CRG1 , { }, 0 }, 
{ CAPET_CRG2 , { }, 0 }, 
{ CAPET_STRMEM , { }, 0 }, 
{ CHR_ADRS , { }, 0 }, 
{ STR_ADRS , { }, 0 }, 
{ CAPET_EXPR , { }, 0 }, 
{ DAXILET_IDT , { }, 0 }, 
{ FARGS_NUMB , { }, 0 }, 
{ FARGS_FLOAT , { }, 0 }, 
{ FARGS_CHR , { }, 0 }, 
{ FARGS_STR , { }, 0 }, 
{ FARGS_IDT_VAL , { }, 0 }, 
{ FARGS_CRG1_VAL , { }, 0 }, 
{ FARGS_CRG2_VAL , { }, 0 }, 
{ FARGS_STRMEM_VAL , { }, 0 }, 
{ FARGS_EXPR_VAL , { }, 0 }, 
{ FPARM_IDT_VAL , { }, 0 }, 
{ POP_OBSTK , { }, 0 }, 
{ GLBMT , { }, 0 }, 
{ FREE_SEC_DYN_STK , { }, 0 }, 
{ KVK , { }, 0 }, 
{ KVK1 , { }, 0 }, 
{ POP_FNSTK , { }, 0 }, 
{ GET_FUNC_RET_RES , { }, 0 }, 
{ PUT_FUNC_RET_RES , { }, 0 }, 
{ KOD_WITH_VAR , { }, 0 }, 
{ KOD_FUNK , { FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_FUNK, TEXT, KOD_FUNK, FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 13 }, 
{ TEXT , { TEXT, KOD_FUNK, FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 7 }, 
{ STANDART , { }, 0 }, 
{ STANDART_FUNK , { }, 0 }, 
{ KVADRAT_KOK , { }, 0 }, 
{ STEKE_QOY , { }, 0 }, 
{ STEKE_QOY_STD , { }, 0 }, 
{ STEKDEN_GOTUR , { }, 0 }, 
{ STEKDEN_GOTUR_STD , { }, 0 }, 
{ SAY , { BRK_VAL, BRK_SEQ, }, 2 }, 
{ SAY_TIP_1 , { SIMPLE_OPER, COMP_OPER, BLOCK, }, 3 }, 
{ CHECK_SAY_TIP_1 , { }, 0 }, 
{ STEP_SAY_TIP_1 , { }, 0 }, 
{ YNT1_FUNC_ARGS , { }, 0 }, 
{ SAY_TIP_2 , { }, 0 }, 
{ SAY_TIP_3 , { }, 0 }, 
{ CHECK_SAY_TIP_2 , { }, 0 }, 
{ STEP_SAY_TIP_2 , { }, 0 }, 
{ CHECK_SAY_TIP_3 , { }, 0 }, 
{ STEP_SAY_TIP_3 , { }, 0 }, 
{ INIT_SAY_TIP_3 , { }, 0 }, 
{ INIT_SAY_TIP_2 , { }, 0 }, 
{ INCREMENT , { NOQTEV, NOQTEV, NOQTEV, IDT, CRG1, CRG2, }, 6 }, 
{ DECREMENT , { NOQTEV, NOQTEV, NOQTEV, IDT, CRG1, CRG2, }, 6 }, 
{ INCREMENT_OPR , { }, 0 }, 
{ DECREMENT_OPR , { }, 0 }, 
{ DAXIL_INSIDE , { }, 0 }, 
{ CAPET_INSIDE , { }, 0 }, 
{ EGER_INSIDE , { }, 0 }, 
{ ARRAY_INDEX , { }, 0 }, 
{ FCALL_VDEC , { }, 0 }, 
{ SHERT_RIGHT , { }, 0 }, 
{ ASGN_RIGHT , { }, 0 }, 
{ SAY_INSIDE , { }, 0 }, 
{ FUNKSIYA_ELAN , { }, 0 }, 
{ BLOCK_INSIDE , { }, 0 }, 
{ SINIF_INSIDE , { }, 0 }, 
{ FREE_CONTEXT , { }, 0 }, 
{ OPERATOR , { }, 0 }, 
{ SIMPLE_OPER , { FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_FUNK, CLSBLK, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_PART, YOXSA, YOXSA, YOXSA, YOXSA, YOXSA_OPER, TEXT, KOD_FUNK, FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 23 }, 
{ EGER_OPER , { }, 0 }, 
{ EGER_YOXSA , { SIMPLE_OPER, COMP_OPER, BLOCK, }, 3 }, 
{ EGER_YOXSA_OPER , { }, 0 }, 
{ NEQEDERKI_OPER , { }, 0 }, 
{ SECIM_OPER , { }, 0 }, 
{ KOD_PART , { FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_FUNK, CLSBLK, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_PART, TEXT, KOD_FUNK, FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 18 }, 
{ SAY_OPER , { }, 0 }, 
{ COMP_OPER , { FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_FUNK, CLSBLK, SIMPLE_OPER, COMP_OPER, BLOCK, KOD_PART, YOXSA, YOXSA, YOXSA, YOXSA, YOXSA_OPER, TEXT, KOD_FUNK, FUNK, KOD_PART, SIMPLE_OPER, COMP_OPER, BLOCK, }, 23 }, 
{ BRK_VAL , { NOQTEV, NOQTEV, NOQTEV, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, GRT, GRT, GRT, GRT, GRT, GRT, GRT, GRT, LES, LES, LES, LES, LES, LES, LES, LES, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, BERABER, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, FERQLI, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, GRTEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, LESEQU, CLSBRK, NOQTEV, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, POSSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, NEGSIG, MULT, MULT, MULT, MULT, MULT, MULT, MULT, MULT, DEL, DEL, DEL, DEL, DEL, DEL, DEL, DEL, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, PRCT, }, 103 }, 
{ ARYBRK_VAL , { }, 0 }, 
{ BRK_SHERT , { VE, VEYA, VE, VEYA, CLSBRK, }, 5 }, 
{ SEQ , { VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, VERGUL, CLSBRK, }, 11 }, 
{ BRK_SEQ , { CLSBRK, }, 1 }, 
{ BRK_EMP , { CLSBRK, }, 1 }, 
{ YOXSA_OPER , { }, 0 },  
};


#endif